// SPDX-License-Identifier: GPL-2.0-only

using System.Globalization;
using System.Reflection;
using System.Text;
using DwarfMapper;
using DwarfMapper.Generator.Diagnostics;
using DwarfMapper.Generator.Tests.Contracts;
using Microsoft.CodeAnalysis;

namespace DwarfMapper.Generator.Tests.SelfValidation;

/// <summary>
///     Documents that are DERIVED from the code, and a test that fails when the committed copy has drifted.
///     <para>
///         The existing scans prove a doc section EXISTS (Scan7), states a fix (Scan8), or names a live test
///         (ClaimMechanismScanTests). None of them can prove the CONTENT is still true — prose asserting
///         "projection honours X" stays green forever after X stops being honoured. That is the decay this
///         file addresses: the two tables below are regenerated from the descriptors and from the generator's
///         observed behaviour, so a drifted document is a build failure rather than a slow lie.
///     </para>
///     <para>
///         The option table is measured, not declared. Every cell comes from compiling the same source with
///         and without the option and looking at what changed, so it cannot describe an intent the code stopped
///         honouring — which is precisely what a hand-maintained support matrix would do.
///     </para>
/// </summary>
public class GeneratedDocsAreCurrentTests
{
    private const string DoNotEdit =
        "<!-- GENERATED FILE — do not edit by hand. Regenerated by GeneratedDocsAreCurrentTests; "
        + "run the test suite and commit the result. -->";

    private static string? _repoRoot;

    private static string RepoRoot
    {
        get
        {
            if (_repoRoot is not null) return _repoRoot;
            var dir = AppContext.BaseDirectory;
            while (dir is not null && !Directory.Exists(Path.Combine(dir, ".git")))
                dir = Path.GetDirectoryName(dir);
            Assert.NotNull(dir);
            return _repoRoot = dir;
        }
    }

    [Fact]
    public void The_diagnostics_index_matches_the_descriptors()
    {
        AssertCurrent(Path.Combine("docs", "generated", "diagnostics-index.md"), RenderDiagnosticsIndex());
    }

    [Fact]
    public void The_option_support_matrix_matches_the_generators_actual_behaviour()
    {
        AssertCurrent(Path.Combine("docs", "generated", "option-support-matrix.md"), RenderOptionMatrix());
    }

    [Fact]
    public void The_api_reference_matches_the_public_surface()
    {
        AssertCurrent(Path.Combine("docs", "generated", "api-reference.md"),
            ApiReferenceRenderer.Render(DoNotEdit));
    }

    [Fact]
    public void The_api_reference_actually_carries_summaries()
    {
        // Without this, a broken XML lookup would render a complete-looking page of empty Summary cells and
        // the drift check would happily hold it stable forever.
        var api = ApiReferenceRenderer.Render(DoNotEdit);
        var rows = api.Split('\n').Where(l => l.StartsWith("| `", StringComparison.Ordinal)).ToList();
        var documented = rows.Count(l => l.TrimEnd().EndsWith('|')
                                         && l.Split('|').Length > 3
                                         && !string.IsNullOrWhiteSpace(l.Split('|')[^2]));

        Assert.True(rows.Count >= 20, $"API reference rendered only {rows.Count} member rows.");
        Assert.True(documented >= rows.Count / 2,
            $"Only {documented} of {rows.Count} rendered members carry a summary — the XML lookup is likely "
            + "broken rather than the code being undocumented.");
    }

    [Fact]
    public void The_generators_are_not_vacuous()
    {
        // Both renderers would "pass" trivially if they produced an empty body and the committed file were
        // also empty. Assert they carry real rows.
        var index = RenderDiagnosticsIndex();
        Assert.True(index.Split('\n').Count(l => l.StartsWith("| `DWARF", StringComparison.Ordinal)) >= 40,
            "The diagnostics index rendered too few rows to be believable.");

        var matrix = RenderOptionMatrix();
        Assert.True(matrix.Split('\n').Count(l => l.StartsWith("| `", StringComparison.Ordinal)) >= 10,
            "The option matrix rendered too few rows to be believable.");
    }

    /// <summary>
    ///     Heal-or-fail: writes the current content so the diff is right there in the working tree, then fails
    ///     so it has to be committed.
    ///     <para>
    ///         `SelfHeal_AnalyzerReleases_rows_are_in_sync` heals and then PASSES. That is deliberately not
    ///         copied here. A silently-healing doc test goes green in CI while the committed document stays
    ///         stale, which leaves the repository in exactly the state this file exists to prevent — the
    ///         generated artefact must be the one people read, not one that only ever exists mid-test-run.
    ///     </para>
    /// </summary>
    private static void AssertCurrent(string relativePath, string expected)
    {
        var path = Path.Combine(RepoRoot, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        var actual = File.Exists(path) ? File.ReadAllText(path) : null;
        if (string.Equals(Normalise(actual), Normalise(expected), StringComparison.Ordinal)) return;

        File.WriteAllText(path, expected);
        Assert.Fail(
            $"{relativePath} was out of date and has been regenerated in your working tree.\n"
            + "Review the diff and commit it. This test fails rather than healing quietly on purpose: a "
            + "healing doc test goes green in CI while the file people actually read stays stale.");
    }

    private static string? Normalise(string? text) =>
        text?.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd();

    // ─────────────────────────────────────────────────────────────────────────
    // Renderers
    // ─────────────────────────────────────────────────────────────────────────

    private static string RenderDiagnosticsIndex()
    {
        var descriptors = typeof(DiagnosticDescriptors)
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(f => f.FieldType == typeof(DiagnosticDescriptor))
            .Select(f => (DiagnosticDescriptor)f.GetValue(null)!)
            .OrderBy(d => d.Id, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("<!-- SPDX-License-Identifier: GPL-2.0-only -->\n");
        sb.Append(DoNotEdit).Append('\n');
        sb.Append("# Diagnostics index\n\n");
        sb.Append("Every diagnostic the generator can report, with its severity, rendered from the descriptor\n");
        sb.Append("definitions themselves. Prose for each id lives in [`diagnostics.md`](../diagnostics.md);\n");
        sb.Append("this table exists so the *list* cannot drift from the code.\n\n");
        sb.Append("| Id | Severity | Title |\n|---|---|---|\n");

        foreach (var d in descriptors)
            sb.Append(CultureInfo.InvariantCulture,
                $"| `{d.Id}` | {d.DefaultSeverity} | {d.Title.ToString(CultureInfo.InvariantCulture)} |\n");

        sb.Append(CultureInfo.InvariantCulture, $"\n{descriptors.Count} diagnostics.\n");
        return sb.ToString();
    }

    private static string RenderOptionMatrix()
    {
        var endpoints = new[]
        {
            Endpoint.CreateMap, Endpoint.UpdateInto, Endpoint.Projection, Endpoint.SpanMap, Endpoint.AsyncStream
        };

        var sb = new StringBuilder();
        sb.Append("<!-- SPDX-License-Identifier: GPL-2.0-only -->\n");
        sb.Append(DoNotEdit).Append('\n');
        sb.Append("# Option support by endpoint\n\n");
        sb.Append("What each class-level `[DwarfMapper(...)]` option actually does at each endpoint. Every cell\n");
        sb.Append("is **measured**, not declared: the same source is compiled with and without the option and\n");
        sb.Append("the difference is recorded. A hand-maintained table would describe what the options were\n");
        sb.Append("*meant* to do, which is how seven silent divergences went unnoticed in this codebase.\n\n");
        sb.Append("| Symbol | Meaning |\n|---|---|\n");
        sb.Append("| honoured | the option changes the generated output |\n");
        sb.Append("| `DWARFnnn` | the option is refused with that diagnostic — visible, not silent |\n");
        sb.Append("| n/a (loud) | not applied, but the build fails anyway, so nothing wrong can ship |\n");
        sb.Append("| **SILENT** | accepted, no effect, compiles — a divergence, and a bug |\n");
        sb.Append("| n/a (no such surface) | the endpoint has nothing this option could configure |\n");
        sb.Append("| not probed | the probe fixture does not trigger this option anywhere, including the |\n");
        sb.Append("| | reference endpoint, so this row measures nothing and claims nothing |\n\n");
        sb.Append("`not probed` is called out rather than shown as a blank or as `SILENT`, because \"the option\n");
        sb.Append("was dropped\" and \"this table does not exercise the option\" are completely different claims\n");
        sb.Append("and must not look alike. Those rows are a gap in the fixtures, not a verdict on the code.\n\n");
        sb.Append("The registry (`[MapTo]`) and co-located host (`[GenerateMap<S,T>]`) front doors are omitted:\n");
        sb.Append("neither has a mapper class to carry a class-level option.\n\n");

        sb.Append("| Option |");
        foreach (var e in endpoints) sb.Append(CultureInfo.InvariantCulture, $" {e} |");
        sb.Append("\n|---|");
        foreach (var _ in endpoints) sb.Append("---|");
        sb.Append('\n');

        foreach (var cell in OptionCatalog.Options)
        {
            sb.Append(CultureInfo.InvariantCulture, $"| `{cell.Name}` |");

            // A row silent at EVERY endpoint means the fixture never triggers the option — a gap in the
            // probe, not a verdict on the code. Gating on the reference endpoint alone was too coarse:
            // ReferenceHandling is silent at CreateMap yet acts at Projection and the span endpoints, and
            // calling that row "not probed" would have hidden a real asymmetry.
            var effects = endpoints
                .Select(e => OptionGaps.StructurallyInapplicable.ContainsKey((cell.Name, e))
                    ? (Effect: OptionEffect.Silent, Detail: "structural")
                    : OptionProbe.Classify(e, cell.NonDefault, cell.Types))
                .ToList();

            if (effects.TrueForAll(x => x.Effect == OptionEffect.Silent))
            {
                foreach (var _ in endpoints) sb.Append(" not probed |");
            }
            else
            {
                foreach (var (effect, detail) in effects)
                {
                    var text = string.Equals(detail, "structural", StringComparison.Ordinal)
                        ? "n/a (no such surface)"
                        : Describe(effect, detail);
                    sb.Append(CultureInfo.InvariantCulture, $" {text} |");
                }
            }

            sb.Append('\n');
        }

        sb.Append("\nOption list and defaults scanned from `DwarfMapperAttribute`; each probe value derived\n");
        sb.Append("from its default (invert a bool, pick another enum member, step an int), so a new option\n");
        sb.Append("appears here without anyone maintaining a list. Probed with: `")
            .Append(string.Join("`, `", OptionCatalog.Options.Select(c => c.NonDefault)))
            .Append("`.\n");
        return sb.ToString();
    }

    private static string Describe(OptionEffect effect, string detail) => effect switch
    {
        OptionEffect.Honoured => "honoured",
        OptionEffect.Refused => "`" + detail + "`",
        OptionEffect.UnhonouredButLoud => "n/a (loud)",
        OptionEffect.Silent => "**SILENT**",
        _ => throw new InvalidOperationException($"Unhandled effect {effect}")
    };

    [Fact]
    public void No_new_silent_cell_appears_in_the_option_matrix()
    {
        var rows = RenderOptionMatrix().Split('\n')
            .Where(l => l.StartsWith("| `", StringComparison.Ordinal))
            .ToList();

        var offenders = rows
            .Where(l => l.Contains("**SILENT**", StringComparison.Ordinal))
            .Select(l => l.Split('`')[1])
            .Where(opt => !OptionGaps.KnownSilent.ContainsKey(opt))
            .ToList();

        Assert.True(offenders.Count == 0,
            "Option(s) newly SILENT at some endpoint — accepted, no effect, and the code still compiles:\n"
            + string.Join("\n", offenders)
            + "\n\nHonour it there, refuse it with a diagnostic, or add it to OptionGaps.KnownSilent with the reason.");
    }

    [Fact]
    public void Every_known_gap_is_still_a_real_gap()
    {
        // A fixed gap left in the list would quietly re-permit the divergence if it ever came back.
        var rows = RenderOptionMatrix().Split('\n')
            .Where(l => l.StartsWith("| `", StringComparison.Ordinal))
            .ToList();

        var stillSilent = rows
            .Where(l => l.Contains("**SILENT**", StringComparison.Ordinal))
            .Select(l => l.Split('`')[1])
            .ToHashSet(StringComparer.Ordinal);

        var fixedOnes = OptionGaps.KnownSilent.Keys.Where(k => !stillSilent.Contains(k)).ToList();
        Assert.True(fixedOnes.Count == 0,
            "OptionGaps.KnownSilent names option(s) that are no longer silent — remove them so the ratchet tightens: "
            + string.Join(", ", fixedOnes));
    }

    [Fact]
    public void Every_option_probed_by_the_matrix_still_exists()
    {
        // A renamed option would otherwise be probed as a no-op forever: [DwarfMapper(Nonsense = true)] does
        // not compile, every cell would read the same at every endpoint, and the table would look uniform and
        // authoritative while measuring nothing.
        var actual = typeof(DwarfMapperAttribute)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanWrite).Select(p => p.Name).ToHashSet(StringComparer.Ordinal);

        var stale = OptionCatalog.Options
            .Select(c => c.Name).Where(o => !actual.Contains(o)).ToList();

        Assert.True(stale.Count == 0, "Matrix probes option(s) that no longer exist: " + string.Join(", ", stale));
    }
}
