// SPDX-License-Identifier: GPL-2.0-only
using System;
using System.Globalization;
using System.Text;

namespace DwarfMapper.Generator.Tests.Fuzzing;

/// <summary>
/// Deterministic synthetic schema generator for property-based fuzz tests.
/// Given an integer seed, produces a complete, valid C# source string that
/// declares Src/Dst classes with identical members and a [DwarfMapper] mapper.
/// Same seed always produces the same source (only new Random(seed) is used).
/// </summary>
internal static class SyntheticSchema
{
    // ── Type pool ──────────────────────────────────────────────────────────
    // Weights: higher index = more likely to be picked (weighted pool via
    // flat-list expansion so we stay on plain Random).

    private static readonly string[] ScalarTypes =
    [
        "int", "int", "int",            // weight 3 – most common
        "long",
        "short",
        "byte",
        "double", "double",
        "float",
        "bool",
        "string", "string",             // weight 2
        "global::System.Guid",
        "global::System.DateTime",
        // ── Extended scalar pool ───────────────────────────────────────────
        "decimal",
        "char",
        "sbyte",
        "uint",
        "ushort",
        "ulong",
        "global::System.DateTimeOffset",
        "global::System.TimeSpan",
    ];
    // ScalarTypes has 21 entries (indices 0..20).

    // All value-type scalars (for T? and collection element types).
    // string is NOT included here — it is a reference type and is not valid for T?.
    // char, decimal, unsigned ints, DateTimeOffset, TimeSpan are all value types.
    private static readonly string[] ValueScalars =
    [
        "int", "long", "short", "byte", "double", "float", "bool",
        "global::System.Guid", "global::System.DateTime",
        "decimal",
        "char",
        "sbyte",
        "uint",
        "ushort",
        "ulong",
        "global::System.DateTimeOffset",
        "global::System.TimeSpan",
    ];

    /// <summary>
    /// Generates a schema suitable for behavioral (value-preserving) property tests.
    /// Identical to <see cref="Generate"/> except <c>HashSet&lt;T&gt;</c> members are excluded:
    /// <c>StructuralComparer</c> compares <c>IEnumerable</c> element-by-element in iteration
    /// order, but <c>HashSet&lt;T&gt;</c> enumeration order is an implementation detail that may
    /// diverge between the source and destination instances even when the sets are equal.
    /// All other types (arrays, lists, nullable value types, enums, nested structs, scalars)
    /// are included as normal.
    /// </summary>
    public static string GenerateBehavioral(int seed)
    {
        var rng = new Random(seed);

        int memberCount = rng.Next(1, 11); // 1..10 members

        var members = new (string Name, string Type)[memberCount];
        for (int i = 0; i < memberCount; i++)
        {
            members[i] = ($"Member{i}", PickTypeBehavioral(rng));
        }

        return BuildSource(members);
    }

    /// <summary>
    /// Generates a schema that sometimes emits advanced features:
    /// [MapDerivedType] dispatch, [FlattenGraph] homo, or top-level collection method.
    /// Deterministic from seed; always produces valid compilable C#.
    /// </summary>
    public static string GenerateWithAdvancedFeatures(int seed)
    {
        var rng = new Random(seed);
        // Pick feature variant based on seed
        int featureVariant = rng.Next(0, 4);
        // 0 = plain (same as Generate), 1 = MapDerivedType, 2 = FlattenGraph homo, 3 = top-level collection

        int memberCount = rng.Next(1, 6); // keep small for advanced features
        var members = new (string Name, string Type)[memberCount];
        for (int i = 0; i < memberCount; i++)
            members[i] = ($"Member{i}", PickTypeBehavioral(rng));

        return featureVariant switch
        {
            1 => BuildSourceWithMapDerivedType(members, seed),
            2 => BuildSourceWithFlattenGraph(members, seed),
            3 => BuildSourceWithTopLevelCollection(members, seed),
            _ => BuildSource(members),
        };
    }

    private static string BuildSourceWithMapDerivedType((string Name, string Type)[] members, int seed)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by SyntheticSchema (advanced:MapDerivedType) — do not edit");
        sb.AppendLine("// seed=" + seed.ToString(CultureInfo.InvariantCulture));
        sb.AppendLine("using DwarfMapper;");
        sb.AppendLine();
        sb.AppendLine("namespace Fuzz;");
        sb.AppendLine();
        sb.AppendLine("public enum FuzzEnum { A, B, C }");
        sb.AppendLine("public enum FuzzEnumL : long { A, B, C }");
        sb.AppendLine();
        sb.AppendLine("public struct FuzzInner { public int A; public float B; }");
        sb.AppendLine();
        // Abstract base and concrete source
        sb.AppendLine("public abstract class Src { public string Tag { get; set; } = \"\"; }");
        sb.AppendLine("public class SrcConcrete : Src");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public abstract class Dst { public string Tag { get; set; } = \"\"; }");
        sb.AppendLine("public class DstConcrete : Dst");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[global::DwarfMapper.DwarfMapper(AutoNest = true)]");
        sb.AppendLine("public partial class FuzzMapper");
        sb.AppendLine("{");
        sb.AppendLine("    [global::DwarfMapper.MapDerivedType<SrcConcrete, DstConcrete>]");
        sb.AppendLine("    public partial Dst Map(Src s);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildSourceWithFlattenGraph((string Name, string Type)[] members, int seed)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by SyntheticSchema (advanced:FlattenGraph) — do not edit");
        sb.AppendLine("// seed=" + seed.ToString(CultureInfo.InvariantCulture));
        sb.AppendLine("using DwarfMapper;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Fuzz;");
        sb.AppendLine();
        sb.AppendLine("public enum FuzzEnum { A, B, C }");
        sb.AppendLine("public enum FuzzEnumL : long { A, B, C }");
        sb.AppendLine();
        sb.AppendLine("public struct FuzzInner { public int A; public float B; }");
        sb.AppendLine();
        // Node types (simple: only scalar members + a single-ref edge)
        sb.AppendLine("public class Src");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name { get; set; } = \"\";");
        sb.AppendLine("    public Src? Next { get; set; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public class Dst");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name { get; set; } = \"\";");
        sb.AppendLine("    public Dst? Next { get; set; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public class SrcRoot { public Src? Entry { get; set; } }");
        sb.AppendLine("public class DstRoot { public global::System.Collections.Generic.List<Dst> Nodes { get; set; } = new(); }");
        sb.AppendLine();
        sb.AppendLine("[global::DwarfMapper.DwarfMapper]");
        sb.AppendLine("public partial class FuzzMapper");
        sb.AppendLine("{");
        sb.AppendLine("    [global::DwarfMapper.FlattenGraph(\"Entry\", \"Nodes\")]");
        sb.AppendLine("    public partial DstRoot Map(SrcRoot r);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildSourceWithTopLevelCollection((string Name, string Type)[] members, int seed)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by SyntheticSchema (advanced:TopLevelCollection) — do not edit");
        sb.AppendLine("// seed=" + seed.ToString(CultureInfo.InvariantCulture));
        sb.AppendLine("using DwarfMapper;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Fuzz;");
        sb.AppendLine();
        sb.AppendLine("public enum FuzzEnum { A, B, C }");
        sb.AppendLine("public enum FuzzEnumL : long { A, B, C }");
        sb.AppendLine();
        sb.AppendLine("public struct FuzzInner { public int A; public float B; }");
        sb.AppendLine();
        sb.AppendLine("public class Src");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public class Dst");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[global::DwarfMapper.DwarfMapper]");
        sb.AppendLine("public partial class FuzzMapper");
        sb.AppendLine("{");
        sb.AppendLine("    public partial Dst Map(Src s);");
        sb.AppendLine("    public partial global::System.Collections.Generic.List<Dst> Map(global::System.Collections.Generic.List<Src> src);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string Generate(int seed)
    {
        var rng = new Random(seed);

        int memberCount = rng.Next(1, 11); // 1..10 members

        var members = new (string Name, string Type)[memberCount];
        for (int i = 0; i < memberCount; i++)
        {
            members[i] = ($"Member{i}", PickType(rng));
        }

        return BuildSource(members);
    }

    // ── Shared source builder ─────────────────────────────────────────────

    private static string BuildSource((string Name, string Type)[] members)
    {
        var sb = new StringBuilder();

        // ── File header ─────────────────────────────────────────────────
        sb.AppendLine("// Auto-generated by SyntheticSchema — do not edit");
        sb.AppendLine("using DwarfMapper;");
        sb.AppendLine();
        sb.AppendLine("namespace Fuzz;");
        sb.AppendLine();

        // ── Shared enums (always emitted so any member using FuzzEnum/FuzzEnumL compiles) ──
        sb.AppendLine("public enum FuzzEnum { A, B, C }");
        sb.AppendLine();
        // Non-default (long) underlying type: exercises by-name mapping across non-int underlying.
        // Member values are kept small (0,1,2) so Convert.ToInt64 in the behavioral oracle is safe.
        sb.AppendLine("public enum FuzzEnumL : long { A, B, C }");
        sb.AppendLine();

        // ── Shared nested struct ─────────────────────────────────────────
        sb.AppendLine("public struct FuzzInner { public int A; public float B; }");
        sb.AppendLine();

        // ── Src class ───────────────────────────────────────────────────
        sb.AppendLine("public class Src");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Dst class (identical members) ───────────────────────────────
        sb.AppendLine("public class Dst");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Mapper ──────────────────────────────────────────────────────
        sb.AppendLine("[global::DwarfMapper.DwarfMapper]");
        sb.AppendLine("public partial class FuzzMapper");
        sb.AppendLine("{");
        sb.AppendLine("    public partial Dst Map(Src s);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Type picker ───────────────────────────────────────────────────────────
    //
    // Category layout (27 slots total, rng.Next(0, 27) → 0..26):
    //
    //   0..20  → raw scalar from ScalarTypes[category]  (21 slots)
    //   21     → T? (nullable value scalar)
    //   22     → T[] (array of scalar/enum element)
    //   23     → List<T>
    //   24     → HashSet<T>
    //   25     → FuzzEnum / FuzzEnumL variants
    //   26     → FuzzInner / FuzzInner[]

    private static string PickType(Random rng)
    {
        int category = rng.Next(0, 27);

        return category switch
        {
            // 0-20 → raw scalar
            >= 0 and <= 20 => ScalarTypes[category],

            // 21 → T? (nullable value scalar)
            21 => PickValueScalar(rng) + "?",

            // 22 → T[] (array of scalar/enum element)
            22 => PickScalarElement(rng) + "[]",

            // 23 → List<T>
            23 => $"global::System.Collections.Generic.List<{PickScalarElement(rng)}>",

            // 24 → HashSet<T>
            24 => $"global::System.Collections.Generic.HashSet<{PickScalarElement(rng)}>",

            // 25 → FuzzEnum or FuzzEnumL variants
            25 => rng.Next(6) switch
            {
                0 => "FuzzEnum",
                1 => "FuzzEnum?",
                2 => "FuzzEnum[]",
                3 => "FuzzEnumL",
                4 => "FuzzEnumL?",
                _ => "FuzzEnumL[]",
            },

            // 26 → FuzzInner or FuzzInner[]
            _ => rng.Next(2) == 0 ? "FuzzInner" : "FuzzInner[]",
        };
    }

    /// <summary>
    /// Type picker for behavioral (value-preserving) tests: identical to <see cref="PickType"/>
    /// but category 24 (HashSet) is redirected to List.  <c>HashSet&lt;T&gt;</c> is excluded
    /// because <c>StructuralComparer</c> walks <c>IEnumerable</c> by position; two equal
    /// <c>HashSet&lt;T&gt;</c> instances may enumerate in different order after a copy.
    /// </summary>
    private static string PickTypeBehavioral(Random rng)
    {
        int category = rng.Next(0, 27);

        return category switch
        {
            >= 0 and <= 20 => ScalarTypes[category],
            21 => PickValueScalar(rng) + "?",
            22 => PickScalarElement(rng) + "[]",
            // 23 and 24 both → List<T> (HashSet excluded for ordering reasons)
            23 or 24 => $"global::System.Collections.Generic.List<{PickScalarElement(rng)}>",
            25 => rng.Next(6) switch
            {
                0 => "FuzzEnum",
                1 => "FuzzEnum?",
                2 => "FuzzEnum[]",
                3 => "FuzzEnumL",
                4 => "FuzzEnumL?",
                _ => "FuzzEnumL[]",
            },
            _ => rng.Next(2) == 0 ? "FuzzInner" : "FuzzInner[]",
        };
    }

    private static string PickValueScalar(Random rng) =>
        ValueScalars[rng.Next(ValueScalars.Length)];

    // For collection element types: value scalars + string (ref is fine in collections)
    private static readonly string[] CollectionElements =
    [
        "int", "int",
        "long",
        "double",
        "float",
        "bool",
        "string",
        "global::System.Guid",
        "global::System.DateTime",
        "FuzzEnum",
        "FuzzEnumL",
        "decimal",
        "char",
        "sbyte",
        "uint",
        "ushort",
        "ulong",
        "global::System.DateTimeOffset",
        "global::System.TimeSpan",
    ];

    private static string PickScalarElement(Random rng) =>
        CollectionElements[rng.Next(CollectionElements.Length)];

    // ── Default initialiser ───────────────────────────────────────────────

    private static string DefaultInit(string type)
    {
        if (type == "string")
            return " = \"\";";

        if (type.EndsWith("[]", StringComparison.Ordinal))
        {
            // Derive element type by stripping trailing []
            string elem = type[..^2];
            // global:: prefix is fine here — Array.Empty<T> just needs the fully-qualified T
            return $" = global::System.Array.Empty<{elem}>();";
        }

        if (type.StartsWith("global::System.Collections.Generic.List<", StringComparison.Ordinal) ||
            type.StartsWith("global::System.Collections.Generic.HashSet<", StringComparison.Ordinal))
            return " = new();";

        // Nullable value types, structs, enums, scalars: no explicit init needed
        return string.Empty;
    }
}
