// SPDX-License-Identifier: GPL-2.0-only
using System;
using System.Globalization;
using System.Text;

namespace DwarfMapper.Generator.Tests.Fuzzing;

/// <summary>
/// Deterministic synthetic schema generator for property-based fuzz tests.
/// Given an integer seed, produces a complete, valid C# source string that
/// declares Src/Dst classes with identical members and a [DwarfMapper] mapper.
/// Same seed always produces the same source (only new Random(seed) is used).
/// </summary>
internal static class SyntheticSchema
{
    // ── Type pool ──────────────────────────────────────────────────────────
    // Weights: higher index = more likely to be picked (weighted pool via
    // flat-list expansion so we stay on plain Random).

    private static readonly string[] ScalarTypes =
    [
        "int", "int", "int",            // weight 3 – most common
        "long",
        "short",
        "byte",
        "double", "double",
        "float",
        "bool",
        "string", "string",             // weight 2
        "global::System.Guid",
        "global::System.DateTime",
    ];

    // All value-type scalars (for T? and collection element types)
    private static readonly string[] ValueScalars =
    [
        "int", "long", "short", "byte", "double", "float", "bool",
        "global::System.Guid", "global::System.DateTime",
    ];

    /// <summary>
    /// Generates a schema suitable for behavioral (value-preserving) property tests.
    /// Identical to <see cref="Generate"/> except <c>HashSet&lt;T&gt;</c> members are excluded:
    /// <c>StructuralComparer</c> compares <c>IEnumerable</c> element-by-element in iteration
    /// order, but <c>HashSet&lt;T&gt;</c> enumeration order is an implementation detail that may
    /// diverge between the source and destination instances even when the sets are equal.
    /// All other types (arrays, lists, nullable value types, enums, nested structs, scalars)
    /// are included as normal.
    /// </summary>
    public static string GenerateBehavioral(int seed)
    {
        var rng = new Random(seed);

        int memberCount = rng.Next(1, 11); // 1..10 members

        var members = new (string Name, string Type)[memberCount];
        for (int i = 0; i < memberCount; i++)
        {
            members[i] = ($"Member{i}", PickTypeBehavioral(rng));
        }

        return BuildSource(members);
    }

    public static string Generate(int seed)
    {
        var rng = new Random(seed);

        int memberCount = rng.Next(1, 11); // 1..10 members

        var members = new (string Name, string Type)[memberCount];
        for (int i = 0; i < memberCount; i++)
        {
            members[i] = ($"Member{i}", PickType(rng));
        }

        return BuildSource(members);
    }

    // ── Shared source builder ─────────────────────────────────────────────

    private static string BuildSource((string Name, string Type)[] members)
    {
        var sb = new StringBuilder();

        // ── File header ─────────────────────────────────────────────────
        sb.AppendLine("// Auto-generated by SyntheticSchema — do not edit");
        sb.AppendLine("using DwarfMapper;");
        sb.AppendLine();
        sb.AppendLine("namespace Fuzz;");
        sb.AppendLine();

        // ── Shared enum (always emitted so any member using FuzzEnum compiles) ──
        sb.AppendLine("public enum FuzzEnum { A, B, C }");
        sb.AppendLine();

        // ── Shared nested struct ─────────────────────────────────────────
        sb.AppendLine("public struct FuzzInner { public int A; public float B; }");
        sb.AppendLine();

        // ── Src class ───────────────────────────────────────────────────
        sb.AppendLine("public class Src");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Dst class (identical members) ───────────────────────────────
        sb.AppendLine("public class Dst");
        sb.AppendLine("{");
        foreach (var (name, type) in members)
            sb.AppendLine(string.Create(CultureInfo.InvariantCulture, $"    public {type} {name} {{ get; set; }}{DefaultInit(type)}"));
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Mapper ──────────────────────────────────────────────────────
        sb.AppendLine("[global::DwarfMapper.DwarfMapper]");
        sb.AppendLine("public partial class FuzzMapper");
        sb.AppendLine("{");
        sb.AppendLine("    public partial Dst Map(Src s);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Type picker ───────────────────────────────────────────────────────

    private static string PickType(Random rng)
    {
        // 13 categories (0-12), weighted by how many slots each gets
        int category = rng.Next(0, 19);

        return category switch
        {
            // 0-12 → raw scalar (13 slots)
            >= 0 and <= 12 => ScalarTypes[category],

            // 13 → T? (nullable value scalar)
            13 => PickValueScalar(rng) + "?",

            // 14 → T[] (array of scalar)
            14 => PickScalarElement(rng) + "[]",

            // 15 → List<T>
            15 => $"global::System.Collections.Generic.List<{PickScalarElement(rng)}>",

            // 16 → HashSet<T>
            16 => $"global::System.Collections.Generic.HashSet<{PickScalarElement(rng)}>",

            // 17 → FuzzEnum or FuzzEnum? or FuzzEnum[]
            17 => rng.Next(3) switch
            {
                0 => "FuzzEnum",
                1 => "FuzzEnum?",
                _ => "FuzzEnum[]",
            },

            // 18 → FuzzInner or FuzzInner[]
            _ => rng.Next(2) == 0 ? "FuzzInner" : "FuzzInner[]",
        };
    }

    /// <summary>
    /// Type picker for behavioral (value-preserving) tests: identical to <see cref="PickType"/>
    /// but category 16 (HashSet) is redirected to List.  <c>HashSet&lt;T&gt;</c> is excluded
    /// because <c>StructuralComparer</c> walks <c>IEnumerable</c> by position; two equal
    /// <c>HashSet&lt;T&gt;</c> instances may enumerate in different order after a copy.
    /// </summary>
    private static string PickTypeBehavioral(Random rng)
    {
        int category = rng.Next(0, 19);

        return category switch
        {
            >= 0 and <= 12 => ScalarTypes[category],
            13 => PickValueScalar(rng) + "?",
            14 => PickScalarElement(rng) + "[]",
            // 15 and 16 both → List<T> (HashSet excluded for ordering reasons)
            15 or 16 => $"global::System.Collections.Generic.List<{PickScalarElement(rng)}>",
            17 => rng.Next(3) switch
            {
                0 => "FuzzEnum",
                1 => "FuzzEnum?",
                _ => "FuzzEnum[]",
            },
            _ => rng.Next(2) == 0 ? "FuzzInner" : "FuzzInner[]",
        };
    }

    private static string PickValueScalar(Random rng) =>
        ValueScalars[rng.Next(ValueScalars.Length)];

    // For collection element types: value scalars + string (ref is fine in collections)
    private static readonly string[] CollectionElements =
    [
        "int", "int",
        "long",
        "double",
        "float",
        "bool",
        "string",
        "global::System.Guid",
        "global::System.DateTime",
        "FuzzEnum",
    ];

    private static string PickScalarElement(Random rng) =>
        CollectionElements[rng.Next(CollectionElements.Length)];

    // ── Default initialiser ───────────────────────────────────────────────

    private static string DefaultInit(string type)
    {
        if (type == "string")
            return " = \"\";";

        if (type.EndsWith("[]", StringComparison.Ordinal))
        {
            // Derive element type by stripping trailing []
            string elem = type[..^2];
            // global:: prefix is fine here — Array.Empty<T> just needs the fully-qualified T
            return $" = global::System.Array.Empty<{elem}>();";
        }

        if (type.StartsWith("global::System.Collections.Generic.List<", StringComparison.Ordinal) ||
            type.StartsWith("global::System.Collections.Generic.HashSet<", StringComparison.Ordinal))
            return " = new();";

        // Nullable value types, structs, enums, scalars: no explicit init needed
        return string.Empty;
    }
}
