// SPDX-License-Identifier: GPL-2.0-only
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using DwarfMapper.Testing;
using DwarfMapper.Generator.Tests.Fuzzing;

namespace DwarfMapper.Generator.Tests;

/// <summary>
/// SELF-VALIDATION: every collection / dictionary type the generator claims to support must actually be
/// GENERATED by the fuzz schema, and must actually be POPULATED by <see cref="ObjectFactory" />.
/// <para>
/// This exists because a "covers every supported linkage" suite silently did not. An
/// <c>IEnumerable&lt;T&gt;</c>-target aliasing bug shipped and survived the whole fuzz + matrix suite for one
/// simple reason: the schema never emitted that shape, so no amount of fuzzing could reach it. Worse,
/// <c>ObjectFactory</c> returned <c>null</c> for interface types and built EMPTY sets/dictionaries — so even a
/// generated shape carried no data to compare or alias.
/// </para>
/// <para>
/// Both failures are invisible from inside the fuzzers: a fuzz test over a shrunken space still goes green.
/// Only a check that compares the GENERATED space against the SUPPORTED space can see the hole — which is
/// what this does. The supported set is read from the generator's own taxonomy (the internal
/// <c>CollectionConverter.TargetKind</c> enum, plus the target names <c>DictionaryConverter</c> matches), so
/// adding a new supported collection type automatically fails this test until the fuzzers cover it. A
/// hand-maintained list would simply drift back out of date.
/// </para>
/// </summary>
public class CollectionCoverageSelfValidationTests
{
    private const int SampleSeeds = 600;

    /// <summary>The collection targets the generator says it supports — its own enum, read reflectively
    /// (the type is internal, and a copied list is exactly what drifts).</summary>
    private static string[] SupportedCollectionKinds()
    {
        var generatorAssembly = typeof(DwarfGenerator).Assembly;
        var targetKind = generatorAssembly.GetType("DwarfMapper.Generator.Pipeline.CollectionConverter+TargetKind");
        Assert.True(targetKind is not null,
            "CollectionConverter.TargetKind not found — the taxonomy moved; this self-validation must be updated.");
        return Enum.GetNames(targetKind!);
    }

    /// <summary>The dictionary targets the generator says it supports — its own <c>DictTargetKind</c> enum, read
    /// reflectively, exactly like <see cref="SupportedCollectionKinds" /> reads TargetKind.</summary>
    private static string[] SupportedDictionaryKinds()
    {
        // Was a source-regex over DictionaryConverter's `switch (name) { case "Dictionary": ... }` labels — which
        // silently depended on every supported kind being wired via a string case ending in "Dictionary". A kind
        // recognised by a non-string path (SpecialType/interface match, as the collection side already uses) would
        // be un-fuzzed with the gate still green. Reflecting the enum makes the supported set authoritative, and
        // matches the collection side's mechanism. (The enum names equal the case labels 1:1 today, so this is
        // behaviour-preserving now and drift-proof going forward.)
        var generatorAssembly = typeof(DwarfGenerator).Assembly;
        var dictKind = generatorAssembly.GetType("DwarfMapper.Generator.Pipeline.DictionaryConverter+DictTargetKind");
        Assert.True(dictKind is not null,
            "DictionaryConverter.DictTargetKind not found — the taxonomy moved; this self-validation must be updated.");
        return Enum.GetNames(dictKind!);
    }

    /// <summary>
    /// Every member type the fuzz schema can actually emit, reduced to its simple type name.
    /// <para>
    /// Samples BOTH pickers. The behavioural (value-preserving) schema legitimately omits unordered
    /// collections — the structural comparer walks IEnumerable by position, and set enumeration order is an
    /// implementation detail that may differ between two equal sets — so those shapes are covered by the
    /// compile-clean schema instead. What matters for coverage is that SOME fuzzer reaches every supported
    /// target; requiring the value oracles to reach an unordered one would just produce flaky tests.
    /// </para>
    /// </summary>
    private static HashSet<string> GeneratedKinds()
    {
        var kinds = new HashSet<string>(StringComparer.Ordinal);
        for (var seed = 0; seed < SampleSeeds; seed++)
        {
            foreach (var source in new[] { SyntheticSchema.Generate(seed), SyntheticSchema.GenerateBehavioral(seed) })
            {
                foreach (var type in MemberTypesOf(source))
                {
                    var kind = KindOf(type);
                    if (kind is not null) kinds.Add(kind);
                }
            }
        }

        return kinds;
    }

    private static IEnumerable<string> MemberTypesOf(string source) =>
        Regex.Matches(source, @"public\s+(?<t>.+?)\s+Member\d+\s*\{\s*get;\s*set;\s*\}")
            .Select(m => m.Groups["t"].Value.Trim());

    /// <summary>Maps a generated member type string onto the generator's taxonomy name.</summary>
    private static string? KindOf(string type)
    {
        if (type.EndsWith("[]", StringComparison.Ordinal)) return "Array";

        var lt = type.IndexOf('<', StringComparison.Ordinal);
        if (lt < 0) return null; // scalar / enum / nested type — not a collection

        var name = type[..lt];
        var dot = name.LastIndexOf('.');
        return dot >= 0 ? name[(dot + 1)..] : name;
    }

    /// <summary>
    /// The targets the COMBINATORIAL matrix actually emits. Coverage in one tier is not coverage in all of
    /// them: the fuzzers vary shapes randomly, but only the combinatorial tier crosses each target against the
    /// other axes (widening variant, cycle mode, update-into, null strategy). A target the fuzzers reach but
    /// the matrix never does is still only half-tested.
    /// </summary>
    private static HashSet<string> CombinatorialKinds()
    {
        var kinds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var cell in CombinatorialSchema.DepthOneMatrix().Concat(CombinatorialSchema.DepthTwoMatrix()))
        {
            foreach (var kind in new[] { KindOf(cell.SrcType), KindOf(cell.DstType) })
            {
                if (kind is not null) kinds.Add(kind);
            }
        }

        return kinds;
    }

    [Fact]
    public void Every_supported_collection_target_is_covered_by_the_COMBINATORIAL_matrix()
    {
        var covered = CombinatorialKinds();
        var missing = SupportedCollectionKinds().Where(k => !covered.Contains(k)).ToList();

        Assert.True(
            missing.Count == 0,
            "These SUPPORTED collection targets never appear in the combinatorial matrix, so they are never "
            + "crossed with the other axes (widening, cycle mode, update-into, null strategy):\n  "
            + string.Join("\n  ", missing)
            + "\n\nAdd them to CombinatorialSchema.DepthOneShapes (and to WrapShape/DefaultInit).");
    }

    [Fact]
    public void Every_supported_dictionary_target_is_covered_by_the_COMBINATORIAL_matrix()
    {
        var covered = CombinatorialKinds();
        var missing = SupportedDictionaryKinds().Where(k => !covered.Contains(k)).ToList();

        Assert.True(
            missing.Count == 0,
            "These SUPPORTED dictionary targets never appear in the combinatorial matrix:\n  "
            + string.Join("\n  ", missing));
    }

    [Fact]
    public void Every_supported_collection_target_is_generated_by_the_fuzz_schema()
    {
        var generated = GeneratedKinds();
        var missing = SupportedCollectionKinds().Where(k => !generated.Contains(k)).ToList();

        Assert.True(
            missing.Count == 0,
            "The fuzz schema never generates these SUPPORTED collection targets, so no fuzz test can reach "
            + "them (this is exactly how the IEnumerable<T> aliasing bug survived the suite):\n  "
            + string.Join("\n  ", missing)
            + "\n\nAdd them to SyntheticSchema's type pickers (and make sure ObjectFactory can populate them).");
    }

    [Fact]
    public void Every_supported_dictionary_target_is_generated_by_the_fuzz_schema()
    {
        var generated = GeneratedKinds();
        var missing = SupportedDictionaryKinds().Where(k => !generated.Contains(k)).ToList();

        Assert.True(
            missing.Count == 0,
            "The fuzz schema never generates these SUPPORTED dictionary targets:\n  "
            + string.Join("\n  ", missing)
            + "\n\nDwarfMapper ships a whole DictionaryConverter; every target it accepts must be fuzzed.");
    }

    [Theory]
    [InlineData(typeof(List<int>))]
    [InlineData(typeof(int[]))]
    [InlineData(typeof(HashSet<int>))]
    [InlineData(typeof(IEnumerable<int>))]
    [InlineData(typeof(ICollection<int>))]
    [InlineData(typeof(IList<int>))]
    [InlineData(typeof(IReadOnlyList<int>))]
    [InlineData(typeof(IReadOnlyCollection<int>))]
    [InlineData(typeof(ISet<int>))]
    [InlineData(typeof(IReadOnlySet<int>))]
    [InlineData(typeof(Dictionary<int, string>))]
    [InlineData(typeof(IDictionary<int, string>))]
    [InlineData(typeof(IReadOnlyDictionary<int, string>))]
    public void ObjectFactory_populates_every_collection_shape_with_actual_data(Type type)
    {
        ArgumentNullException.ThrowIfNull(type);

        // The mirror-image hole: a shape the schema CAN emit but the factory cannot fill is just as invisible.
        // Interface-typed members came back null, and sets/dictionaries came back empty, so the fuzzers were
        // comparing nothing at all for those members.
        var instance = ObjectFactory.Create(type, new Random(12345), 0);

        Assert.True(instance is not null, $"ObjectFactory returned NULL for {type.Name} — every fuzz test "
                                          + "silently skipped this shape.");

        var count = instance switch
        {
            System.Collections.ICollection c => c.Count,
            System.Collections.IEnumerable e => e.Cast<object?>().Count(),
            _ => 0,
        };

        Assert.True(count > 0, $"ObjectFactory produced an EMPTY {type.Name} — the fuzzers were comparing "
                               + "zero elements, so any element-level bug in this shape was unreachable.");
    }
}
