// SPDX-License-Identifier: GPL-2.0-only

// 32 — The mapper is a stateless, allocation-free class, so all of these reach the same generated code; pick
// whichever fits the call site. Example 12 shows the extension and DI for one pair; this collects the styles
// side by side, which is what the README and the "common changes" guide quote.

using DwarfMapper.Extensions;              // surfaces the generated order.ToOrderView() extension
using Microsoft.Extensions.DependencyInjection;

namespace DwarfMapper.Gallery.Guides.G32;

[DwarfMapper]
[GenerateMap<Order, OrderView>]
public partial class CallStyles { }

[DocExample(32, Tier.Guides, "Ways to call a mapper",
    Shows = "instance, the generated extension method, and `AddDwarfMappers()` DI")]
public static class Example
{
    public static void Run()
    {
        var order = new Order { Id = 3, FullName = "Alan Turing", Total = 1m };

        // <snippet: four-ways-to-call>
        // 1. Instance — new it (it holds no state, so this is free) or inject it.
        var byInstance = new CallStyles().Map(order);

        // 2. Convenience extension method, generated by default into DwarfMapper.Extensions.
        var byExtension = order.ToOrderView();      // named after the target type

        // 3. Dependency injection, when Microsoft.Extensions.DependencyInjection is referenced.
        using var provider = new ServiceCollection().AddDwarfMappers().BuildServiceProvider();
        var byDi = provider.GetRequiredService<CallStyles>().Map(order);
        // </snippet>

        Console.WriteLine(
            $"32 Ways to call       -> {byInstance.FullName} / {byExtension.FullName} / {byDi.FullName}");
    }
}
