// SPDX-License-Identifier: GPL-2.0-only

using System.Text;
using DwarfMapper.Generator.Model;

namespace DwarfMapper.Generator.Pipeline;

/// <summary>
///     Emits the two assembly-wide convenience outputs that aggregate across every generated mapper in this
///     assembly (both <c>[DwarfMapper]</c> classes and co-located <c>[GenerateMap]</c> hosts):
///     <list type="number">
///         <item>
///             <description>the extension-method facade (<c>order.ToOrderDto()</c>), in <c>DwarfMapper.Extensions</c>;</description>
///         </item>
///         <item>
///             <description>the <c>IServiceCollection.AddDwarfMappers()</c> DI registration (only when DI is referenced).</description>
///         </item>
///     </list>
///     Both are driven off the <see cref="MapperClassModel" /> set collected from the pipeline, so cross-mapper
///     name collisions can be de-duplicated in one place.
/// </summary>
internal static class AggregateEmitter
{
    private const string Header =
        "// <auto-generated/>\n// SPDX-License-Identifier: GPL-2.0-only\n#nullable enable\n";

    private static readonly char[] BadTypeChars = { '<', '>', '[', ']', '*', '?', '(', ')', ' ', '+', ',' };

    /// <summary>
    ///     Builds the extension facade for all eligible mappers, or <c>null</c> when there is nothing to emit.
    /// </summary>
    public static (string? Source, IReadOnlyList<(string SourceType, string ExtName)> Collisions)
        EmitExtensions(IReadOnlyList<MapperClassModel> models, bool publicExtensions)
    {
        var candidates = new List<ExtCandidate>();

        foreach (var model in models)
        {
            if (!model.GenerateExtensions || !model.HasParameterlessCtor) continue;

            var mapperFullName = "global::" + (string.IsNullOrEmpty(model.Namespace)
                ? model.ClassName
                : model.Namespace + "." + model.ClassName);

            foreach (var method in model.Methods)
            {
                if (!IsEligible(method)) continue;

                var extName = "To" + ShortName(method.ReturnTypeFullName);
                candidates.Add(new ExtCandidate(
                    method.ParameterTypeFullName, method.ReturnTypeFullName, extName, mapperFullName, method.MethodName,
                    method.ParameterIsPublicType, method.ReturnIsPublicType));
            }
        }

        // Group by (source-type, extension-name). A group with >1 candidate is an ambiguous signature: it is
        // dropped (the instance methods still work) and surfaced as DWARF058 by the caller rather than silently
        // vanishing.
        var groups = candidates
            .GroupBy(c => c.SourceType + " " + c.ExtName, StringComparer.Ordinal)
            .ToList();
        var collisions = groups
            .Where(g => g.Count() > 1)
            .Select(g => (g.First().SourceType, g.First().ExtName))
            .OrderBy(c => c.ExtName, StringComparer.Ordinal)
            .ThenBy(c => c.SourceType, StringComparer.Ordinal)
            .ToList();
        var kept = groups
            .Where(g => g.Count() == 1)
            .Select(g => g.First())
            .OrderBy(c => c.ExtName, StringComparer.Ordinal)
            .ThenBy(c => c.SourceType, StringComparer.Ordinal)
            .ToList();

        if (kept.Count == 0) return (null, collisions);

        var fields = kept
            .Select(c => c.MapperFullName)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append(Header).Append('\n');
        sb.AppendLine("namespace DwarfMapper.Extensions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Convenience extension methods generated by DwarfMapper. Each forwards to a cached, stateless");
        sb.AppendLine(
            "/// mapper instance — e.g. <c>order.ToOrderDto()</c>. Add <c>using DwarfMapper.Extensions;</c> to use them.");
        sb.AppendLine("/// Disable for a mapper with <c>[DwarfMapper(GenerateExtensions = false)]</c>.");
        sb.AppendLine("/// </summary>");
        sb.Append(publicExtensions ? "public" : "internal").AppendLine(" static class DwarfMapperGeneratedExtensions");
        sb.AppendLine("{");

        foreach (var mapper in fields)
            sb.Append("    private static readonly ").Append(mapper).Append(' ')
                .Append(FieldName(mapper)).Append(" = new();").Append('\n');

        foreach (var c in kept)
        {
            sb.AppendLine();
            sb.Append("    /// <summary>Maps <c>").Append(c.SourceType).Append("</c> to <c>")
                .Append(c.TargetType).Append("</c>.</summary>").Append('\n');
            sb.Append("    ").Append(publicExtensions && c.SourceIsPublic && c.TargetIsPublic ? "public" : "internal")
                .Append(" static ").Append(c.TargetType).Append(' ').Append(c.ExtName)
                .Append("(this ").Append(c.SourceType).Append(" source)").Append('\n');
            sb.Append("        => ").Append(FieldName(c.MapperFullName)).Append('.')
                .Append(c.MapperMethod).Append("(source);").Append('\n');
        }

        sb.AppendLine("}");
        return (sb.ToString(), collisions);
    }

    /// <summary>
    ///     Builds the <c>AddDwarfMappers()</c> DI registration extension, or <c>null</c> when there are no mappers.
    ///     Emitted only when the compilation references <c>Microsoft.Extensions.DependencyInjection.Abstractions</c>.
    ///     The class is emitted in the assembly's own namespace (<paramref name="assemblyNamespace" />), not the
    ///     universally-imported <c>Microsoft.Extensions.DependencyInjection</c>, so the extension method does not
    ///     collide across assemblies when one references several mapper-bearing assemblies (CS0121).
    /// </summary>
    public static string? EmitServiceCollection(IReadOnlyList<MapperClassModel> models, string assemblyNamespace)
    {
        var mapperTypes = models
            .Select(m =>
                "global::" + (string.IsNullOrEmpty(m.Namespace) ? m.ClassName : m.Namespace + "." + m.ClassName))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        if (mapperTypes.Count == 0) return null;

        var sb = new StringBuilder();
        sb.Append(Header).Append('\n');
        sb.Append("namespace ").Append(assemblyNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine(
            "/// <summary>DI registration for every generated mapper in this assembly (both <c>[DwarfMapper]</c> classes and co-located <c>[GenerateMap]</c> hosts). Call <c>services.AddDwarfMappers()</c> (this class lives in the assembly's own namespace to avoid cross-assembly collisions).</summary>");
        sb.AppendLine("public static class DwarfMapperServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every generated DwarfMapper mapper in this assembly as a singleton");
        sb.AppendLine(
            "    /// (mappers are stateless), so they can be injected directly. No reflection or assembly scan.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDwarfMappers(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var t in mapperTypes)
            sb.Append(
                    "        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<")
                .Append(t).Append(">(services);").Append('\n');
        // Also register the ambient IDwarfMapper facade (stateless; resolves from the process-wide registry),
        // so consumers can inject it for cross-assembly maps. TryAdd: harmless if several assemblies do it.
        sb.AppendLine(
            "        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::DwarfMapper.IDwarfMapper>(services, global::DwarfMapper.DwarfMapperFacade.Instance);");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    ///     Builds the ambient cross-assembly self-registration: a <c>[ModuleInitializer]</c> that registers
    ///     every eligible stateless, PUBLIC-typed create-map (<c>T Map(S)</c>) into
    ///     <see cref="global::DwarfMapper.DwarfMapperRegistry" /> at load (zero reflection, AOT-safe), plus the
    ///     matching <c>[assembly: DwarfProvidesMap(...)]</c> manifest read by the validation root. Only maps
    ///     whose source AND destination are effectively public are registered — internal types cannot be named
    ///     by another assembly, so they have no cross-assembly (ambient) meaning. Returns the source (or
    ///     <c>null</c> when nothing to register) and the full names of mappers that have eligible public maps but
    ///     no parameterless constructor (reported as DWARF062 — they cannot self-register without DI).
    /// </summary>
    public static (string? Source, IReadOnlyList<string> Unregisterable) EmitAmbientRegistration(
        IReadOnlyList<MapperClassModel> models)
    {
        var regs = new List<(string Source, string Dest, string Field, string Method)>();
        var fields = new SortedSet<string>(StringComparer.Ordinal);
        var unregisterable = new List<string>();
        var seenPairs = new HashSet<string>(StringComparer.Ordinal);

        foreach (var model in models.OrderBy(m => m.HintName, StringComparer.Ordinal))
        {
            var eligible = model.Methods
                .Where(IsAmbientRegisterable)
                .ToList();
            if (eligible.Count == 0) continue;

            var mapperFullName = "global::" + (string.IsNullOrEmpty(model.Namespace)
                ? model.ClassName
                : model.Namespace + "." + model.ClassName);

            if (!model.HasParameterlessCtor)
            {
                unregisterable.Add(mapperFullName);
                continue;
            }

            foreach (var method in eligible
                         .OrderBy(m => m.ParameterTypeFullName, StringComparer.Ordinal)
                         .ThenBy(m => m.ReturnTypeFullName, StringComparer.Ordinal))
            {
                // First provider of a (source, dest) pair in this assembly wins; a second same-assembly
                // provider is dropped here (cross-assembly ambiguity is tracked by the registry at runtime).
                if (!seenPairs.Add(method.ParameterTypeFullName + " " + method.ReturnTypeFullName)) continue;

                fields.Add(mapperFullName);
                regs.Add((method.ParameterTypeFullName, method.ReturnTypeFullName, FieldName(mapperFullName),
                    method.MethodName));
            }
        }

        if (regs.Count == 0) return (null, unregisterable);

        var sb = new StringBuilder();
        sb.Append(Header).Append('\n');
        foreach (var r in regs)
            sb.Append("[assembly: global::DwarfMapper.DwarfProvidesMap(typeof(")
                .Append(r.Source).Append("), typeof(").Append(r.Dest).Append("))]").Append('\n');
        sb.AppendLine();
        sb.AppendLine("namespace DwarfMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine(
            "/// <summary>Self-registers this assembly's stateless, public-typed create-maps into the ambient");
        sb.AppendLine(
            "/// <c>DwarfMapperRegistry</c> at module load (zero reflection, AOT-safe), so any assembly can resolve");
        sb.AppendLine("/// them through <c>IDwarfMapper</c> without referencing this one.</summary>");
        sb.AppendLine("internal static class __DwarfMapperAmbientRegistration");
        sb.AppendLine("{");
        foreach (var field in fields)
            sb.Append("    private static readonly ").Append(field).Append(' ')
                .Append(FieldName(field)).Append(" = new();").Append('\n');
        sb.AppendLine();
        // Run-once: the CLR fires __Register from the module initializer, but DwarfMap.Validate() also calls it
        // (to be independent of module-init ordering). Without this guard the second run re-registers every
        // pair; DwarfMapperRegistry.Register treats a re-add as a competing provider and would falsely flag the
        // assembly's own maps as ambiguous. Idempotent + thread-safe so any caller order is safe.
        sb.AppendLine("    private static int __registered;");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void __Register()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (global::System.Threading.Interlocked.Exchange(ref __registered, 1) != 0) return;");
        foreach (var r in regs)
            sb.Append("        global::DwarfMapper.DwarfMapperRegistry.Register(typeof(")
                .Append(r.Source).Append("), typeof(").Append(r.Dest).Append("), static __s => ")
                .Append(r.Field).Append('.').Append(r.Method).Append("((").Append(r.Source).Append(")__s));")
                .Append('\n');
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return (sb.ToString(), unregisterable);
    }

    /// <summary>
    ///     A map is placed in the ambient registry iff it is an eligible plain <c>T Map(S)</c> entry whose source
    ///     AND destination are effectively public (internal types have no cross-assembly meaning). Shared by the
    ///     registration emitter and <see cref="CollectProvidedPairs" /> so the emitted <c>Provides</c> manifest and
    ///     the root-validation view never drift.
    /// </summary>
    private static bool IsAmbientRegisterable(MapMethodModel m)
    {
        return IsEligible(m) && m.ParameterIsPublicType && m.ReturnIsPublicType;
    }

    /// <summary>
    ///     The (source, destination) pairs this assembly self-registers into the ambient registry — i.e. the
    ///     <c>Provides</c> set the validation root treats as available from this compilation. Mirrors exactly what
    ///     <see cref="EmitAmbientRegistration" /> registers (public-typed maps on parameterless-ctor mappers, first
    ///     provider per pair).
    /// </summary>
    public static IReadOnlyList<(string Source, string Destination)> CollectProvidedPairs(
        IReadOnlyList<MapperClassModel> models)
    {
        var pairs = new List<(string, string)>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var model in models.OrderBy(m => m.HintName, StringComparer.Ordinal))
        {
            if (!model.HasParameterlessCtor) continue;
            foreach (var method in model.Methods
                         .Where(IsAmbientRegisterable)
                         .OrderBy(m => m.ParameterTypeFullName, StringComparer.Ordinal)
                         .ThenBy(m => m.ReturnTypeFullName, StringComparer.Ordinal))
                if (seen.Add(method.ParameterTypeFullName + " " + method.ReturnTypeFullName))
                    pairs.Add((method.ParameterTypeFullName, method.ReturnTypeFullName));
        }

        return pairs;
    }

    /// <summary>
    ///     A method is eligible for a convenience extension only if it is a plain, single-argument
    ///     <c>TTarget Map(TSource)</c> public entry returning a plain named type. Everything with a special
    ///     shape (update-into, span, async stream, projection, derived dispatch, extra parameters, collection
    ///     conversion, void return) is excluded.
    /// </summary>
    private static bool IsEligible(MapMethodModel m)
    {
        if (m.IsProjection || m.IsUpdateInto || m.IsSpanMap || m.IsAsyncStreamMap ||
            m.IsTopLevelCollectionConversion)
            return false;

        if (m.DerivedTypeArms.Count > 0 || m.ExtraParameters.Count > 0) return false;

        // Must be a real public entry the facade can call: a user partial method or a [GenerateMap] method.
        if (!m.IsPartial && !m.EmitAsNonPartial) return false;

        if (m.Accessibility != "public" && m.Accessibility != "internal") return false;

        return IsPlainNamedType(m.ParameterTypeFullName) && IsPlainNamedType(m.ReturnTypeFullName);
    }

    /// <summary>
    ///     True for a fully-qualified, non-generic, non-array named type — the only shapes whose short name is a
    ///     safe identifier and whose use as <c>this</c>/return type can't introduce a malformed signature.
    /// </summary>
    private static bool IsPlainNamedType(string fullyQualified)
    {
        return fullyQualified.StartsWith("global::", StringComparison.Ordinal)
               && fullyQualified.IndexOfAny(BadTypeChars) < 0;
    }

    private static string ShortName(string fullyQualified)
    {
        var s = fullyQualified.StartsWith("global::", StringComparison.Ordinal)
            ? fullyQualified.Substring("global::".Length)
            : fullyQualified;
        var dot = s.LastIndexOf('.');
        return dot >= 0 ? s.Substring(dot + 1) : s;
    }

    /// <summary>Stable, unique private-field identifier for a mapper's cached singleton.</summary>
    private static string FieldName(string mapperFullName)
    {
        var s = mapperFullName.StartsWith("global::", StringComparison.Ordinal)
            ? mapperFullName.Substring("global::".Length)
            : mapperFullName;
        return "__" + s.Replace('.', '_');
    }

    /// <summary>One candidate convenience extension: <c>{ExtName}(this {Source}) => {Mapper}.{Method}(...)</c>.</summary>
    private readonly struct ExtCandidate
    {
        public ExtCandidate(string sourceType, string targetType, string extName, string mapperFullName,
            string mapperMethod, bool sourceIsPublic, bool targetIsPublic)
        {
            SourceType = sourceType;
            TargetType = targetType;
            ExtName = extName;
            MapperFullName = mapperFullName;
            MapperMethod = mapperMethod;
            SourceIsPublic = sourceIsPublic;
            TargetIsPublic = targetIsPublic;
        }

        public string SourceType { get; }
        public string TargetType { get; }
        public string ExtName { get; }
        public string MapperFullName { get; }
        public string MapperMethod { get; }
        public bool SourceIsPublic { get; }
        public bool TargetIsPublic { get; }
    }
}
