// SPDX-License-Identifier: GPL-2.0-only
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DwarfMapper.Generator.Model;

namespace DwarfMapper.Generator.Pipeline;

/// <summary>
/// Emits the two assembly-wide convenience outputs that aggregate across every <c>[DwarfMapper]</c> class:
/// <list type="number">
/// <item><description>the extension-method facade (<c>order.ToOrderDto()</c>), in <c>DwarfMapper.Extensions</c>;</description></item>
/// <item><description>the <c>IServiceCollection.AddDwarfMappers()</c> DI registration (only when DI is referenced).</description></item>
/// </list>
/// Both are driven off the <see cref="MapperClassModel"/> set collected from the pipeline, so cross-mapper
/// name collisions can be de-duplicated in one place.
/// </summary>
internal static class AggregateEmitter
{
    private const string Header =
        "// <auto-generated/>\n// SPDX-License-Identifier: GPL-2.0-only\n#nullable enable\n";

    /// <summary>One candidate convenience extension: <c>{ExtName}(this {Source}) => {Mapper}.{Method}(...)</c>.</summary>
    private readonly struct ExtCandidate
    {
        public ExtCandidate(string sourceType, string targetType, string extName, string mapperFullName, string mapperMethod)
        {
            SourceType = sourceType;
            TargetType = targetType;
            ExtName = extName;
            MapperFullName = mapperFullName;
            MapperMethod = mapperMethod;
        }

        public string SourceType { get; }
        public string TargetType { get; }
        public string ExtName { get; }
        public string MapperFullName { get; }
        public string MapperMethod { get; }
    }

    /// <summary>
    /// Builds the extension facade for all eligible mappers, or <c>null</c> when there is nothing to emit.
    /// </summary>
    public static (string? Source, IReadOnlyList<(string SourceType, string ExtName)> Collisions)
        EmitExtensions(IReadOnlyList<MapperClassModel> models)
    {
        var candidates = new List<ExtCandidate>();

        foreach (var model in models)
        {
            if (!model.GenerateExtensions || !model.HasParameterlessCtor)
            {
                continue;
            }

            var mapperFullName = "global::" + (string.IsNullOrEmpty(model.Namespace)
                ? model.ClassName
                : model.Namespace + "." + model.ClassName);

            foreach (var method in model.Methods)
            {
                if (!IsEligible(method))
                {
                    continue;
                }

                var extName = "To" + ShortName(method.ReturnTypeFullName);
                candidates.Add(new ExtCandidate(
                    method.ParameterTypeFullName, method.ReturnTypeFullName, extName, mapperFullName, method.MethodName));
            }
        }

        // Group by (source-type, extension-name). A group with >1 candidate is an ambiguous signature: it is
        // dropped (the instance methods still work) and surfaced as DWARF058 by the caller rather than silently
        // vanishing.
        var groups = candidates
            .GroupBy(c => c.SourceType + " " + c.ExtName, System.StringComparer.Ordinal)
            .ToList();
        var collisions = groups
            .Where(g => g.Count() > 1)
            .Select(g => (g.First().SourceType, g.First().ExtName))
            .OrderBy(c => c.ExtName, System.StringComparer.Ordinal)
            .ThenBy(c => c.SourceType, System.StringComparer.Ordinal)
            .ToList();
        var kept = groups
            .Where(g => g.Count() == 1)
            .Select(g => g.First())
            .OrderBy(c => c.ExtName, System.StringComparer.Ordinal)
            .ThenBy(c => c.SourceType, System.StringComparer.Ordinal)
            .ToList();

        if (kept.Count == 0)
        {
            return (null, collisions);
        }

        var fields = kept
            .Select(c => c.MapperFullName)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(n => n, System.StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append(Header).Append('\n');
        sb.AppendLine("namespace DwarfMapper.Extensions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Convenience extension methods generated by DwarfMapper. Each forwards to a cached, stateless");
        sb.AppendLine("/// mapper instance — e.g. <c>order.ToOrderDto()</c>. Add <c>using DwarfMapper.Extensions;</c> to use them.");
        sb.AppendLine("/// Disable for a mapper with <c>[DwarfMapper(GenerateExtensions = false)]</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class DwarfMapperGeneratedExtensions");
        sb.AppendLine("{");

        foreach (var mapper in fields)
        {
            sb.Append("    private static readonly ").Append(mapper).Append(' ')
              .Append(FieldName(mapper)).Append(" = new();").Append('\n');
        }

        foreach (var c in kept)
        {
            sb.AppendLine();
            sb.Append("    /// <summary>Maps <c>").Append(c.SourceType).Append("</c> to <c>")
              .Append(c.TargetType).Append("</c>.</summary>").Append('\n');
            sb.Append("    public static ").Append(c.TargetType).Append(' ').Append(c.ExtName)
              .Append("(this ").Append(c.SourceType).Append(" source)").Append('\n');
            sb.Append("        => ").Append(FieldName(c.MapperFullName)).Append('.')
              .Append(c.MapperMethod).Append("(source);").Append('\n');
        }

        sb.AppendLine("}");
        return (sb.ToString(), collisions);
    }

    /// <summary>
    /// Builds the <c>AddDwarfMappers()</c> DI registration extension, or <c>null</c> when there are no mappers.
    /// Emitted only when the compilation references <c>Microsoft.Extensions.DependencyInjection.Abstractions</c>.
    /// </summary>
    public static string? EmitServiceCollection(IReadOnlyList<MapperClassModel> models)
    {
        var mapperTypes = models
            .Select(m => "global::" + (string.IsNullOrEmpty(m.Namespace) ? m.ClassName : m.Namespace + "." + m.ClassName))
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(n => n, System.StringComparer.Ordinal)
            .ToList();

        if (mapperTypes.Count == 0)
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.Append(Header).Append('\n');
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>DI registration for every <c>[DwarfMapper]</c> mapper in this assembly.</summary>");
        sb.AppendLine("public static class DwarfMapperServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every generated DwarfMapper mapper in this assembly as a singleton");
        sb.AppendLine("    /// (mappers are stateless), so they can be injected directly. No reflection or assembly scan.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDwarfMappers(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var t in mapperTypes)
        {
            sb.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<")
              .Append(t).Append(">(services);").Append('\n');
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// A method is eligible for a convenience extension only if it is a plain, single-argument
    /// <c>TTarget Map(TSource)</c> public entry returning a plain named type. Everything with a special
    /// shape (update-into, span, async stream, projection, derived dispatch, extra parameters, collection
    /// conversion, void return) is excluded.
    /// </summary>
    private static bool IsEligible(MapMethodModel m)
    {
        if (m.IsProjection || m.IsUpdateInto || m.IsSpanMap || m.IsAsyncStreamMap ||
            m.IsTopLevelCollectionConversion)
        {
            return false;
        }

        if (m.DerivedTypeArms.Count > 0 || m.ExtraParameters.Count > 0)
        {
            return false;
        }

        // Must be a real public entry the facade can call: a user partial method or a [GenerateMap] method.
        if (!m.IsPartial && !m.EmitAsNonPartial)
        {
            return false;
        }

        if (m.Accessibility != "public" && m.Accessibility != "internal")
        {
            return false;
        }

        return IsPlainNamedType(m.ParameterTypeFullName) && IsPlainNamedType(m.ReturnTypeFullName);
    }

    /// <summary>
    /// True for a fully-qualified, non-generic, non-array named type — the only shapes whose short name is a
    /// safe identifier and whose use as <c>this</c>/return type can't introduce a malformed signature.
    /// </summary>
    private static bool IsPlainNamedType(string fullyQualified)
        => fullyQualified.StartsWith("global::", System.StringComparison.Ordinal)
           && fullyQualified.IndexOfAny(BadTypeChars) < 0;

    private static readonly char[] BadTypeChars = { '<', '>', '[', ']', '*', '?', '(', ')', ' ', '+', ',' };

    private static string ShortName(string fullyQualified)
    {
        var s = fullyQualified.StartsWith("global::", System.StringComparison.Ordinal)
            ? fullyQualified.Substring("global::".Length)
            : fullyQualified;
        var dot = s.LastIndexOf('.');
        return dot >= 0 ? s.Substring(dot + 1) : s;
    }

    /// <summary>Stable, unique private-field identifier for a mapper's cached singleton.</summary>
    private static string FieldName(string mapperFullName)
    {
        var s = mapperFullName.StartsWith("global::", System.StringComparison.Ordinal)
            ? mapperFullName.Substring("global::".Length)
            : mapperFullName;
        return "__" + s.Replace('.', '_');
    }
}
