// SPDX-License-Identifier: GPL-2.0-only
using System.Text;
using DwarfMapper.Generator.Model;

namespace DwarfMapper.Generator.Pipeline;

internal static class MapEmitter
{
    public static string Emit(MapperClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// SPDX-License-Identifier: GPL-2.0-only");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(model.Accessibility).Append(" partial class ").AppendLine(model.ClassName);
        sb.AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, method, "    ");
        }

        foreach (var synth in model.SynthesizedMethods)
        {
            sb.AppendLine();
            sb.Append(synth.Code);
        }

        foreach (var rt in model.RoundTrips)
        {
            sb.AppendLine();
            sb.Append("    public void VerifyRoundTrip_").Append(rt.ForwardName).AppendLine("(int seed = 12345, int iterations = 100)");
            sb.Append("        => global::DwarfMapper.Testing.RoundTrip.Verify<")
              .Append(rt.SourceTypeFullName).Append(", ").Append(rt.DtoTypeFullName).Append(">(")
              .Append(rt.ForwardName).Append(", ").Append(rt.BackwardName).AppendLine(", seed, iterations);");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, MapMethodModel method, string indent)
    {
        // ── Determine depth-guard context ────────────────────────────────────────
        // A synthesized method that is recursion-capable gets extra (ctx, depth) parameters
        // and a depth guard at the top of its body.
        // A public (partial) method that calls recursion-capable synthesized methods creates
        // a DwarfRefContext upfront and passes it with depth=0 to the first tracked calls.
        var isSynthesizedRecursive = !method.IsPartial && method.IsRecursionCapable;
        var isPublicWithCtx = method.IsPartial && method.IsRecursionCapable;

        // Param names used in emission:
        //   public-with-ctx     : ctx variable = "__dwarf_ctx", depth passed = "0"
        //   synthesized-recursive: ctx param   = "ctx",         depth passed = "depth + 1"
        var ctxVarName  = isPublicWithCtx ? "__dwarf_ctx" : "ctx";
        var depthPassFwd = isSynthesizedRecursive ? "depth + 1" : "0";

        // OnCycle = SetNull (None mode): recursion-capable reference pairs wrap their body in an
        // on-stack guard. Gated on a reference-type source (value types are never tracked) and on
        // recursion-capability (only re-entrant pairs need the guard). When active, the standalone
        // depth guard and before-hooks are emitted INSIDE the guarded body instead of here.
        var willUseSetNullPath = method.IsSetNullMode && method.ParameterIsReferenceType
            && (isSynthesizedRecursive || isPublicWithCtx);

        // Zero-alloc span map: void Map(ReadOnlySpan<S> src, Span<D> dst).
        if (method.IsSpanMap)
        {
            EmitSpanMapMethod(sb, method, indent);
            return;
        }

        // Async streaming map: IAsyncEnumerable<D> Map(IAsyncEnumerable<S> src).
        if (method.IsAsyncStreamMap)
        {
            EmitAsyncStreamMapMethod(sb, method, indent);
            return;
        }

        // Update-into-existing: void/T Map(S src, T dest) — assign onto an existing instance.
        if (method.IsUpdateInto)
        {
            EmitUpdateIntoMethod(sb, method, indent);
            return;
        }

        // IsPartial=true → user-declared partial: emit "public partial T Name(S s)"
        // IsPartial=false → synthesized private: plain or depth-guarded
        if (method.IsPartial)
        {
            // Public declared method — signature never changes (no ctx param for callers).
            // [GenerateMap]-synthesized entries are emitted as a FULL method (no `partial` keyword),
            // since the user never declared a partial to implement.
            sb.Append(indent).Append(method.Accessibility).Append(method.EmitAsNonPartial ? " " : " partial ")
              .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
              .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName).AppendLine(")");
        }
        else if (isSynthesizedRecursive)
        {
            // Depth-guarded synthesized private method: extra (DwarfRefContext ctx, int depth) params.
            sb.Append(indent).Append("private ")
              .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
              .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName)
              .Append(", global::DwarfMapper.DwarfRefContext ctx, int depth")
              .AppendLine(")");
        }
        else
        {
            sb.Append(indent).Append("private ")
              .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
              .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName).AppendLine(")");
        }
        sb.Append(indent).AppendLine("{");

        if (method.ParameterIsReferenceType)
        {
            if (method.IsPartial)
            {
                // Public partial mapper: null source is a programming error → loud ArgumentNullException.
                // Use the BCL throw-helper ArgumentNullException.ThrowIfNull: the actual `throw` lives in a
                // [DoesNotReturn]/NoInlining helper, so this hot method stays small IL and inlines readily
                // (an inline `throw new …` bloats IL and can block inlining). Same loud-on-null semantics;
                // the paramName is captured via [CallerArgumentExpression].
                sb.Append(indent).Append("    global::System.ArgumentNullException.ThrowIfNull(")
                  .Append(method.ParameterName).AppendLine(");");
            }
            else if (method.ReturnIsReferenceType)
            {
                // Synthesized private nested mapper with a REFERENCE target: null source → null target
                // (defensive, not a throw). The calling mapper owns the outer null-check.
                sb.Append(indent).Append("    if (").Append(method.ParameterName)
                  .AppendLine(" is null) return null!;");
            }
            else
            {
                // Synthesized private nested mapper with a VALUE-TYPE target: cannot return null
                // (would be CS0037), so a null source is a loud failure rather than a silent default.
                sb.Append(indent).Append("    if (").Append(method.ParameterName)
                  .Append(" is null) throw new global::System.InvalidOperationException(\"Cannot map a null '")
                  .Append(method.ParameterTypeFullName)
                  .Append("' to value-type '").Append(method.ReturnTypeFullName).AppendLine("'.\");");
            }
        }

        // ── DwarfRefContext creation (public methods calling recursion-capable pairs) ─
        if (isPublicWithCtx)
        {
            sb.Append(indent).Append("    var __dwarf_ctx = new global::DwarfMapper.DwarfRefContext(")
              .Append(method.MaxDepth.ToString(System.Globalization.CultureInfo.InvariantCulture));
            // Plan 19 C2: Preserve mode passes preserve:true to allocate the identity map.
            if (method.IsPreserveMode)
                sb.Append(", true");
            // OnCycle = SetNull (None mode) passes setNull:true to allocate the on-stack guard.
            else if (method.IsSetNullMode)
                sb.Append(", preserve: false, setNull: true");
            sb.AppendLine(");");
        }

        // ── Depth guard (non-Preserve synthesized recursion-capable methods only) ────────
        // For Preserve-mode recursion-capable methods the depth guard is emitted INSIDE
        // EmitPreserveRegisterBeforePopulate, AFTER TryGetReference (B1 fix: cached nodes
        // return without consuming depth). For non-Preserve mode, there is no identity map,
        // so the guard is emitted here unconditionally before any construction logic.
        // Condition: depth >= ctx.MaxDepth (not strictly >, so that MaxDepth=8 allows depths 0..7
        // and throws at depth 8 — meaning chains of length > MaxDepth throw as specified).
        if (isSynthesizedRecursive && !method.IsPreserveMode && !willUseSetNullPath)
        {
            sb.Append(indent).AppendLine("    if (depth >= ctx.MaxDepth)");
            sb.Append(indent).Append("        throw new global::DwarfMapper.DwarfMappingDepthException(ctx.MaxDepth, depth);");
            sb.AppendLine();
        }

        // ── Fix 1: Top-level collection/dictionary-returning method ───────────────────
        // When IsTopLevelCollectionConversion=true, Members[0] is a sentinel with
        // SourceName="" and ConverterMethod = the synthesized collection/dict helper.
        // Emit: return helper(param);  [or with ctx,0 if the helper needs depth ctx]
        if (method.IsTopLevelCollectionConversion && method.Members.Count == 1)
        {
            var tlm = method.Members[0];
            var p = method.ParameterName;
            sb.Append(indent).Append("    return ").Append(tlm.ConverterMethod!).Append('(').Append(p);
            if (tlm.ConverterNeedsDepthCtx)
                sb.Append(", ").Append(ctxVarName).Append(", 0");
            sb.AppendLine(");");
            sb.Append(indent).AppendLine("}");
            return;
        }
        // ── End Fix 1 ────────────────────────────────────────────────────────────────

        if (method.IsProjection)
        {
            sb.Append(indent).Append("    return global::System.Linq.Queryable.Select(")
              .Append(method.ParameterName).Append(", __s => ");

            var projMembers = method.ProjectionMembers;

            if (projMembers.Count == 1 && projMembers[0].TargetName.Length == 0)
            {
                // Ctor-only projection: the entire lambda body is the single inline expression.
                // e.g.  __s => new global::D.DstRec(x: __s.X, y: __s.Y)
                sb.Append(projMembers[0].InlineExpr).AppendLine(");");
            }
            else if (projMembers.Count > 0)
            {
                // Member-init projection with inline expression fragments (Plan 19D recursive resolver).
                sb.AppendLine("new " + method.ElementTargetTypeFullName);
                sb.Append(indent).AppendLine("    {");
                foreach (var pm in projMembers)
                {
                    sb.Append(indent).Append("        ").Append(pm.TargetName)
                      .Append(" = ").Append(pm.InlineExpr).AppendLine(",");
                }
                sb.Append(indent).AppendLine("    });");
            }
            else
            {
                // Fallback: legacy flat Members path (backward compat / error-case placeholder).
                sb.AppendLine("new " + method.ElementTargetTypeFullName);
                sb.Append(indent).AppendLine("    {");
                foreach (var member in method.Members)
                {
                    sb.Append(indent).Append("        ").Append(member.TargetName)
                      .Append(" = __s.").Append(member.SourceName).AppendLine(",");
                }
                sb.Append(indent).AppendLine("    });");
            }

            sb.Append(indent).AppendLine("}");
            return;
        }

        // ── Plan 21: [MapDerivedType] derived-dispatch switch ────────────────
        if (method.DerivedTypeArms.Count > 0)
        {
            EmitDerivedDispatchBody(sb, method, indent);
            sb.Append(indent).AppendLine("}");
            return;
        }

        // Emit before-hooks here ONLY for non-Preserve paths.
        // For Preserve-mode recursion-capable methods (both public and synthesized),
        // before-hooks are emitted INSIDE EmitPreserveRegisterBeforePopulate AFTER TryGetReference
        // (B2 fix: a cached node returns before the hook fires — hooks must not run twice).
        var willUsePreservePath = method.IsPreserveMode && method.ParameterIsReferenceType
            && (isSynthesizedRecursive || isPublicWithCtx);
        if (!willUsePreservePath && !willUseSetNullPath)
        {
            foreach (var before in method.BeforeHooks)
            {
                sb.Append(indent).Append("    ").Append(before).Append('(').Append(method.ParameterName).AppendLine(");");
            }
        }

        var hasCtorArgs = method.ConstructorArguments.Count > 0;
        var hasInitMembers = method.Members.Count > 0;
        var hasAfter = method.AfterHooks.Count > 0;

        // ── Plan 19 C2: Register-before-populate (Preserve mode, recursion-capable) ──
        // Both synthesized recursion-capable methods AND public methods under Preserve mode
        // use register-before-populate to reconstruct arbitrary topologies:
        //   1. Check identity map: if already registered, return the cached target.
        //   2. Construct the target (ctor args only).
        //   3. Register in the identity map BEFORE populating members → breaks ALL cycles.
        //   4. Populate members via individual assignment statements.
        //   5. Return.
        //
        // The public method MUST also register-before-populate because the public source object
        // (`n`) can be encountered again via a recursive call (e.g. n.Self = n → self-loop;
        // a.Next = b, b.Next = a → 2-node cycle). If we don't register before populating,
        // the back-edge call re-constructs a NEW target instead of returning the in-progress one.
        //
        // Gate: isPreserve AND source is reference type (value types are never tracked; the
        // null check above has already returned/thrown for null sources).
        if (method.IsPreserveMode && method.ParameterIsReferenceType
            && (isSynthesizedRecursive || isPublicWithCtx))
        {
            EmitPreserveRegisterBeforePopulate(sb, method, indent, ctxVarName, depthPassFwd, isPublicWithCtx);
            sb.Append(indent).AppendLine("}");
            return;
        }

        // ── OnCycle = SetNull (None mode): on-stack-guarded body ─────────────────────
        // Recursion-capable reference pairs break cycles by nulling the re-entrant back-edge.
        if (willUseSetNullPath)
        {
            EmitSetNullGuardedBody(sb, method, indent, ctxVarName, depthPassFwd, isPublicWithCtx);
            sb.Append(indent).AppendLine("}");
            return;
        }

        // Begin construction expression: "var __dwarf_target = new T(...)" or "return new T(...)".
        sb.Append(indent).Append("    ").Append(hasAfter ? "var __dwarf_target = new " : "return new ")
          .Append(method.ReturnTypeFullName);

        if (hasCtorArgs)
        {
            // Named constructor arguments (clarity + safe against reordering).
            sb.AppendLine("(");
            var ctorArgs = method.ConstructorArguments;
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                var arg = ctorArgs[i];
                sb.Append(indent).Append("        ").Append(arg.TargetName).Append(": ");
                AppendValueExpression(sb, arg, method.ParameterName, ctxVarName, depthPassFwd);
                if (i < ctorArgs.Count - 1)
                    sb.AppendLine(",");
                else
                    sb.Append(')');
            }

            if (hasInitMembers)
            {
                sb.AppendLine();
                sb.Append(indent).AppendLine("    {");
                foreach (var member in method.Members)
                {
                    sb.Append(indent).Append("        ").Append(member.TargetName).Append(" = ");
                    AppendValueExpression(sb, member, method.ParameterName, ctxVarName, depthPassFwd);
                    sb.AppendLine(",");
                }
                sb.Append(indent).AppendLine("    };");
            }
            else
            {
                sb.AppendLine(";");
            }
        }
        else
        {
            // Original object-initializer only path (no ctor args).
            sb.AppendLine();
            sb.Append(indent).AppendLine("    {");
            foreach (var member in method.Members)
            {
                sb.Append(indent).Append("        ").Append(member.TargetName).Append(" = ");
                AppendValueExpression(sb, member, method.ParameterName, ctxVarName, depthPassFwd);
                sb.AppendLine(",");
            }
            sb.Append(indent).AppendLine("    };");
        }

        if (hasAfter)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("    ").Append(after.Name).Append('(');
                if (after.TakesSource)
                {
                    sb.Append(method.ParameterName).Append(", ");
                }
                if (after.TargetByRef)
                {
                    sb.Append("ref ");
                }
                sb.Append("__dwarf_target").AppendLine(");");
            }
            sb.Append(indent).Append("    return __dwarf_target;").AppendLine();
        }

        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Emits the register-before-populate multi-statement form for a recursion-capable
    /// method under <c>ReferenceHandling = Preserve</c>.
    ///
    /// For synthesized private methods:
    /// <code>
    ///   if (ctx.TryGetReference(s, out var __dwarf_cached)) return (T)__dwarf_cached;
    ///   var __dwarf_t = new T(ctorArg1: ..., ctorArg2: ...);
    ///   ctx.SetReference(s, __dwarf_t);
    ///   __dwarf_t.Member1 = ...;
    ///   return __dwarf_t;
    /// </code>
    ///
    /// For public partial methods (isPublicMethod=true):
    /// <code>
    ///   // Before hooks run first (if any)
    ///   if (__dwarf_ctx.TryGetReference(n, out var __dwarf_cached)) return (T)__dwarf_cached;
    ///   var __dwarf_t = new T(...);
    ///   __dwarf_ctx.SetReference(n, __dwarf_t);
    ///   __dwarf_t.Member1 = ...;
    ///   // After hooks run on __dwarf_t (if any)
    ///   return __dwarf_t;
    /// </code>
    ///
    /// The TryGetReference/SetReference checks use the reference-identity comparer
    /// (ReferenceEqualityComparer.Instance) so value-equal records are never merged.
    /// </summary>
    private static void EmitPreserveRegisterBeforePopulate(
        StringBuilder sb, MapMethodModel method, string indent,
        string ctxVarName, string depthPassFwd, bool isPublicMethod)
    {
        var p = method.ParameterName;

        // Step 1: Identity-map check — if already mapped, return the cached target.
        // IMPORTANT: this MUST come before the depth guard (B1 fix).
        // A shared/cyclic node first reached via a short path is registered in the identity map.
        // When encountered again via a longer path that would exceed MaxDepth, the cached instance
        // must be returned immediately without consuming depth or throwing. The depth guard only
        // applies to genuinely-fresh nodes that have NOT been mapped yet.
        // Cast is safe: the identity map is keyed by the source object; the value was stored
        // by this same method, so it is always of type T.
        sb.Append(indent).Append("    if (").Append(ctxVarName).Append(".TryGetReference(")
          .Append(p).Append(", out var __dwarf_cached)) return (")
          .Append(method.ReturnTypeFullName).AppendLine(")__dwarf_cached;");

        // Depth guard for synthesized recursion-capable methods only (public methods have no depth guard).
        // Condition: depth >= ctx.MaxDepth so that MaxDepth=8 allows depths 0..7 and throws at 8.
        // Placed AFTER TryGetReference (B1 fix): a cached node returns immediately above; only
        // genuinely-fresh, unregistered nodes check depth here.
        if (!isPublicMethod)
        {
            sb.Append(indent).AppendLine("    if (depth >= ctx.MaxDepth)");
            sb.Append(indent).Append("        throw new global::DwarfMapper.DwarfMappingDepthException(ctx.MaxDepth, depth);");
            sb.AppendLine();
        }

        // Before hooks (public methods only) — emitted AFTER TryGetReference (B2 fix).
        // A cached node returns immediately above; hooks must not fire again for the same source.
        if (isPublicMethod)
        {
            foreach (var before in method.BeforeHooks)
            {
                sb.Append(indent).Append("    ").Append(before).Append('(').Append(p).AppendLine(");");
            }
        }

        // Step 2: Construct target. For the register-before-populate algorithm, the ctor
        // must be called WITHOUT graph-node members that participate in the cycle.
        // DWARF030 is emitted at generator time for any ctor arg that is recursion-capable.
        var hasCtorArgs = method.ConstructorArguments.Count > 0;
        sb.Append(indent).Append("    var __dwarf_t = new ").Append(method.ReturnTypeFullName);

        if (hasCtorArgs)
        {
            sb.AppendLine("(");
            var ctorArgs = method.ConstructorArguments;
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                var arg = ctorArgs[i];
                sb.Append(indent).Append("        ").Append(arg.TargetName).Append(": ");
                AppendValueExpression(sb, arg, p, ctxVarName, depthPassFwd);
                if (i < ctorArgs.Count - 1)
                    sb.AppendLine(",");
                else
                    sb.AppendLine(");");
            }
        }
        else
        {
            sb.AppendLine("();");
        }

        // Step 3: Register BEFORE populating members — the critical invariant.
        // This ensures any recursive call to map the same source object returns THIS instance,
        // not a newly constructed duplicate. Breaks all cycles (self-loops, 2-node, N-node, diamonds).
        sb.Append(indent).Append("    ").Append(ctxVarName).Append(".SetReference(")
          .Append(p).AppendLine(", __dwarf_t);");

        // Step 4: Populate settable members via individual assignment statements.
        // Safe because __dwarf_t is in the identity map before any member recursion.
        foreach (var member in method.Members)
        {
            sb.Append(indent).Append("    __dwarf_t.").Append(member.TargetName).Append(" = ");
            AppendValueExpression(sb, member, p, ctxVarName, depthPassFwd);
            sb.AppendLine(";");
        }

        // After hooks (public methods only), then return.
        if (isPublicMethod && method.AfterHooks.Count > 0)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("    ").Append(after.Name).Append('(');
                if (after.TakesSource) sb.Append(p).Append(", ");
                if (after.TargetByRef) sb.Append("ref ");
                sb.Append("__dwarf_t").AppendLine(");");
            }
        }

        // Step 5: Return the fully-populated target.
        sb.Append(indent).AppendLine("    return __dwarf_t;");
    }

    /// <summary>
    /// Emits an async streaming map <c>IAsyncEnumerable&lt;D&gt; Map(IAsyncEnumerable&lt;S&gt; src)</c> as an
    /// <c>async</c> iterator: <c>await foreach (var item in src) yield return conv(item);</c>. Lazily
    /// transforms the source sequence element-by-element (no buffering; streaming/back-pressure preserved).
    /// </summary>
    private static void EmitAsyncStreamMapMethod(StringBuilder sb, MapMethodModel method, string indent)
    {
        var src = method.ParameterName;

        sb.Append(indent).Append(method.Accessibility).Append(" async partial ")
          .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
          .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(src).AppendLine(")");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    await foreach (var __item in ").Append(src).AppendLine(")");

        var elem = method.Members.Count > 0 ? method.Members[0] : null;
        sb.Append(indent).Append("        yield return ");
        if (elem?.ConverterMethod is null)
        {
            // Direct/implicit element conversion.
            sb.Append("__item");
        }
        else
        {
            sb.Append(elem.ConverterMethod).Append("(__item)");
        }
        sb.AppendLine(";");
        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Emits a zero-alloc span map <c>void Map(ReadOnlySpan&lt;S&gt; src, Span&lt;D&gt; dst)</c>: a defensive
    /// length guard (destination too small → <c>ArgumentException</c>, never silent truncation) then an
    /// element loop <c>dst[i] = conv(src[i])</c> (or a direct/implicit assignment when no converter is
    /// needed). No allocation; the caller owns the destination buffer.
    /// </summary>
    private static void EmitSpanMapMethod(StringBuilder sb, MapMethodModel method, string indent)
    {
        var src = method.ParameterName;
        var dst = method.SpanTargetParameterName;

        sb.Append(indent).Append(method.Accessibility).Append(" partial void ").Append(method.MethodName)
          .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(src).Append(", ")
          .Append(method.ReturnTypeFullName).Append(' ').Append(dst).AppendLine(")");
        sb.Append(indent).AppendLine("{");

        // Defensive length guard — never silently truncate.
        sb.Append(indent).Append("    if (").Append(dst).Append(".Length < ").Append(src).AppendLine(".Length)");
        sb.Append(indent).Append("        throw new global::System.ArgumentException(")
          .Append("\"DwarfMapper: destination span (length \" + ").Append(dst).Append(".Length + \") is smaller than the source span (length \" + ")
          .Append(src).Append(".Length + \").\", nameof(").Append(dst).AppendLine("));");

        sb.Append(indent).Append("    for (int __i = 0; __i < ").Append(src).AppendLine(".Length; __i++)");
        sb.Append(indent).Append("        ").Append(dst).Append("[__i] = ");

        var elem = method.Members.Count > 0 ? method.Members[0] : null;
        if (elem?.ConverterMethod is null)
        {
            // Direct/implicit element assignment (e.g. int → long widening).
            sb.Append(src).Append("[__i]");
        }
        else
        {
            sb.Append(elem.ConverterMethod).Append('(').Append(src).Append("[__i])");
        }
        sb.AppendLine(";");

        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Emits an update-into-existing method <c>void/T Map(S src, T dest)</c>: null-guards both
    /// parameters, then assigns each settable destination member from the source (no construction,
    /// target identity preserved). Returns <c>dest</c> for the non-void form. Recursion-capable nested
    /// members (e.g. a self-referential collection) get a fresh <c>DwarfRefContext</c> for the depth
    /// guard, so deep/cyclic data throws <see cref="DwarfMapper.DwarfMappingDepthException"/> rather
    /// than StackOverflowing.
    /// </summary>
    private static void EmitUpdateIntoMethod(StringBuilder sb, MapMethodModel method, string indent)
    {
        var src = method.ParameterName;
        var dst = method.UpdateTargetParameterName;
        var retType = method.UpdateReturnsVoid ? "void" : method.ReturnTypeFullName;

        sb.Append(indent).Append(method.Accessibility).Append(" partial ").Append(retType).Append(' ')
          .Append(method.MethodName).Append('(')
          .Append(method.ParameterTypeFullName).Append(' ').Append(src).Append(", ")
          .Append(method.ReturnTypeFullName).Append(' ').Append(dst).AppendLine(")");
        sb.Append(indent).AppendLine("{");

        // Null guards (loud — mapping into/from null is a programming error). BCL throw-helper keeps
        // the hot path small IL (see the public-mapper note above).
        if (method.ParameterIsReferenceType)
            sb.Append(indent).Append("    global::System.ArgumentNullException.ThrowIfNull(").Append(src).AppendLine(");");
        sb.Append(indent).Append("    global::System.ArgumentNullException.ThrowIfNull(").Append(dst).AppendLine(");");

        var anyCtx = false;
        foreach (var m in method.Members) { if (m.ConverterNeedsDepthCtx) { anyCtx = true; break; } }
        const string ctxVar = "__dwarf_ctx";
        if (anyCtx)
            sb.Append(indent).Append("    var ").Append(ctxVar)
              .Append(" = new global::DwarfMapper.DwarfRefContext(")
              .Append(method.MaxDepth.ToString(System.Globalization.CultureInfo.InvariantCulture)).AppendLine(");");

        foreach (var before in method.BeforeHooks)
            sb.Append(indent).Append("    ").Append(before).Append('(').Append(src).AppendLine(");");

        foreach (var member in method.Members)
        {
            sb.Append(indent).Append("    ").Append(dst).Append('.').Append(member.TargetName).Append(" = ");
            AppendValueExpression(sb, member, src, ctxVar, "0");
            sb.AppendLine(";");
        }

        foreach (var after in method.AfterHooks)
        {
            sb.Append(indent).Append("    ").Append(after.Name).Append('(');
            if (after.TakesSource) sb.Append(src).Append(", ");
            if (after.TargetByRef) sb.Append("ref ");
            sb.Append(dst).AppendLine(");");
        }

        if (!method.UpdateReturnsVoid)
            sb.Append(indent).Append("    return ").Append(dst).AppendLine(";");

        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Emits the on-stack-guarded body for a recursion-capable reference pair under
    /// <c>ReferenceHandling = None</c> with <c>OnCycle = SetNull</c>.
    ///
    /// <code>
    ///   if (!ctx.TryEnterNode(s)) return null!;   // re-entrant back-edge → break the cycle with null
    ///   try
    ///   {
    ///       if (depth >= ctx.MaxDepth) throw ...;  // synthesized only — backstop for deep ACYCLIC chains
    ///       // before hooks (public method only)
    ///       return new T(...) { Member = map(s.Member, ctx, depth + 1), ... };
    ///   }
    ///   finally { ctx.ExitNode(s); }
    /// </code>
    ///
    /// Unlike Preserve, the target is NOT registered: SetNull tracks the SOURCE stack, so a shared
    /// but acyclic node (a diamond) is re-mapped on each path (its source leaves the stack before
    /// the second parent is visited) and only true ancestor cycles are nulled. Construction is the
    /// normal object-initializer form (members recurse with <c>ctx, depth + 1</c>); the guard simply
    /// nulls the back-edge when a node is re-entered while still on the stack.
    /// </summary>
    private static void EmitSetNullGuardedBody(
        StringBuilder sb, MapMethodModel method, string indent,
        string ctxVarName, string depthPassFwd, bool isPublicMethod)
    {
        var p = method.ParameterName;

        // Back-edge guard: a source already on the active mapping stack → break cycle with null.
        // null! suppresses the nullable-return warning (the caller assigns it to a member; a
        // non-nullable target member simply receives null, matching System.Text.Json IgnoreCycles).
        sb.Append(indent).Append("    if (!").Append(ctxVarName).Append(".TryEnterNode(")
          .Append(p).AppendLine(")) return null!;");
        sb.Append(indent).AppendLine("    try");
        sb.Append(indent).AppendLine("    {");

        // Depth guard (synthesized recursion-capable methods only) — a backstop for deep ACYCLIC
        // chains. Cycles are already broken by the on-stack guard above, so this rarely fires under
        // SetNull, but a 100k-deep acyclic chain still must throw rather than StackOverflow.
        if (!isPublicMethod)
        {
            sb.Append(indent).AppendLine("        if (depth >= ctx.MaxDepth)");
            sb.Append(indent).AppendLine("            throw new global::DwarfMapper.DwarfMappingDepthException(ctx.MaxDepth, depth);");
        }

        // Before hooks (public method only; synthesized pairs carry none). Emitted after a successful
        // enter so they fire exactly once for the root.
        if (isPublicMethod)
        {
            foreach (var before in method.BeforeHooks)
            {
                sb.Append(indent).Append("        ").Append(before).Append('(').Append(p).AppendLine(");");
            }
        }

        var hasCtorArgs = method.ConstructorArguments.Count > 0;
        var hasInitMembers = method.Members.Count > 0;
        var hasAfter = method.AfterHooks.Count > 0;

        // Construction — identical shape to the normal None path, indented inside the try block.
        sb.Append(indent).Append("        ").Append(hasAfter ? "var __dwarf_target = new " : "return new ")
          .Append(method.ReturnTypeFullName);

        if (hasCtorArgs)
        {
            sb.AppendLine("(");
            var ctorArgs = method.ConstructorArguments;
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                var arg = ctorArgs[i];
                sb.Append(indent).Append("            ").Append(arg.TargetName).Append(": ");
                AppendValueExpression(sb, arg, p, ctxVarName, depthPassFwd);
                if (i < ctorArgs.Count - 1)
                    sb.AppendLine(",");
                else
                    sb.Append(')');
            }

            if (hasInitMembers)
            {
                sb.AppendLine();
                sb.Append(indent).AppendLine("        {");
                foreach (var member in method.Members)
                {
                    sb.Append(indent).Append("            ").Append(member.TargetName).Append(" = ");
                    AppendValueExpression(sb, member, p, ctxVarName, depthPassFwd);
                    sb.AppendLine(",");
                }
                sb.Append(indent).AppendLine("        };");
            }
            else
            {
                sb.AppendLine(";");
            }
        }
        else
        {
            sb.AppendLine();
            sb.Append(indent).AppendLine("        {");
            foreach (var member in method.Members)
            {
                sb.Append(indent).Append("            ").Append(member.TargetName).Append(" = ");
                AppendValueExpression(sb, member, p, ctxVarName, depthPassFwd);
                sb.AppendLine(",");
            }
            sb.Append(indent).AppendLine("        };");
        }

        if (hasAfter)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("        ").Append(after.Name).Append('(');
                if (after.TakesSource) sb.Append(p).Append(", ");
                if (after.TargetByRef) sb.Append("ref ");
                sb.Append("__dwarf_target").AppendLine(");");
            }
            sb.Append(indent).AppendLine("        return __dwarf_target;");
        }

        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("    finally");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        ").Append(ctxVarName).Append(".ExitNode(").Append(p).AppendLine(");");
        sb.Append(indent).AppendLine("    }");
    }

    /// <summary>
    /// Emits the switch-expression dispatch body for a [MapDerivedType]-annotated method.
    /// Generated switch is most-derived-first (sorted by MapperExtractor).
    /// Wildcard arm throws ArgumentException (loud, never silent).
    /// </summary>
    private static void EmitDerivedDispatchBody(
        StringBuilder sb, MapMethodModel method, string indent)
    {
        var p = method.ParameterName;
        var arms = method.DerivedTypeArms;
        var hasAfter = method.AfterHooks.Count > 0;

        // Determine ctx var and depth arg for this dispatch method.
        // isPublicWithCtx: public method that creates __dwarf_ctx.
        // isSynthesizedRecursive: private recursion-capable (unlikely for a dispatch method but safe).
        var isSynthesizedRecursive = !method.IsPartial && method.IsRecursionCapable;
        var isPublicWithCtx = method.IsPartial && method.IsRecursionCapable;
        var ctxVarName  = isPublicWithCtx ? "__dwarf_ctx" : "ctx";
        var depthPassFwd = isSynthesizedRecursive ? "depth + 1" : "0";

        // Before hooks (if any)
        foreach (var before in method.BeforeHooks)
        {
            sb.Append(indent).Append("    ").Append(before).Append('(').Append(p).AppendLine(");");
        }

        // Switch expression
        var switchLine = hasAfter
            ? $"    var __dwarf_target = {p} switch"
            : $"    return {p} switch";
        sb.Append(indent).AppendLine(switchLine);
        sb.Append(indent).AppendLine("    {");

        foreach (var arm in arms)
        {
            sb.Append(indent).Append("        ")
              .Append(arm.SrcFqn).Append(" __s => ").Append(arm.ConverterMethod).Append("(__s");
            if (arm.ConverterNeedsDepthCtx)
                sb.Append(", ").Append(ctxVarName).Append(", ").Append(depthPassFwd);
            sb.AppendLine("),");
        }

        // Wildcard arm: throw ArgumentException for unregistered runtime type
        sb.Append(indent).Append("        ")
          .Append("_ => throw new global::System.ArgumentException(")
          .Append("\"DwarfMapper: no [MapDerivedType] registered for runtime type '\" + ")
          .Append(p).Append(".GetType()")
          .Append(" + \"' mapping to '").Append(method.ReturnTypeFullName).Append("'.\", nameof(")
          .Append(p).AppendLine(")),");

        sb.Append(indent).AppendLine("    };");

        // After hooks (if any), then return
        if (hasAfter)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("    ").Append(after.Name).Append('(');
                if (after.TakesSource) sb.Append(p).Append(", ");
                if (after.TargetByRef) sb.Append("ref ");
                sb.Append("__dwarf_target").AppendLine(");");
            }
            sb.Append(indent).AppendLine("    return __dwarf_target;");
        }
    }

    /// <summary>
    /// Append the value expression for a single mapping (ctor arg or object-initializer member)
    /// to <paramref name="sb"/>. Does NOT append a trailing comma or newline.
    /// </summary>
    /// <param name="ctxVarName">
    /// Name of the <c>DwarfRefContext</c> variable in scope (e.g. <c>"ctx"</c> or
    /// <c>"__dwarf_ctx"</c>). Only used when <see cref="MemberMap.ConverterNeedsDepthCtx"/> is true.
    /// </param>
    /// <param name="depthArg">
    /// The depth argument to forward (e.g. <c>"depth + 1"</c> from a recursion-capable synthesized
    /// method, or <c>"0"</c> from the public entry point). Only used when
    /// <see cref="MemberMap.ConverterNeedsDepthCtx"/> is true.
    /// </param>
    private static void AppendValueExpression(
        StringBuilder sb, MemberMap member, string paramName,
        string ctxVarName = "ctx", string depthArg = "0")
    {
        // [MapValue]: a raw constant/computed expression assigned verbatim — no source access.
        if (member.ValueExpression is not null)
        {
            sb.Append(member.ValueExpression);
            return;
        }

        // NullableProject: both source and target are Nullable<T>. Emit null-preserving ternary:
        //   src.X.HasValue ? Conv(src.X.Value) : null
        // C# 9+ target-typed conditional unifies U (from Conv) and null into U?.
        if (member.NullHandling == Model.NullHandling.NullableProject)
        {
            var srcExpr = paramName + "." + member.SourceName;
            if (member.ConverterMethod is not null)
            {
                sb.Append(srcExpr).Append(".HasValue ? ")
                  .Append(member.ConverterMethod).Append('(').Append(srcExpr).Append(".Value) : null");
            }
            else
            {
                // Defensive fallback: T?→U? where T→U is implicit (direct assignment).
                sb.Append(srcExpr);
            }
            return;
        }

        // Build the "inner value access" — the nullable-unwrapped (or plain) source expression.
        string innerAccess;
        switch (member.NullHandling)
        {
            case Model.NullHandling.ThrowIfNull:
                innerAccess = paramName + "." + member.SourceName
                    + " ?? throw new global::System.InvalidOperationException(\"Source member '"
                    + member.SourceName + "' was null\")";
                break;
            case Model.NullHandling.ValueOrDefault:
                innerAccess = paramName + "." + member.SourceName + ".GetValueOrDefault()";
                break;
            default:
                innerAccess = paramName + "." + member.SourceName;
                break;
        }

        // Wrap the inner access with the converter if present.
        if (member.ConverterMethod is not null)
        {
            if (member.NullHandling != Model.NullHandling.None)
            {
                // Both converter and null-handling: Conv(src.X ?? throw ...) or Conv(src.X.GetValueOrDefault())
                if (member.ConverterNeedsDepthCtx)
                    sb.Append(member.ConverterMethod).Append('(').Append(innerAccess)
                      .Append(", ").Append(ctxVarName).Append(", ").Append(depthArg).Append(')');
                else
                    sb.Append(member.ConverterMethod).Append('(').Append(innerAccess).Append(')');
            }
            else
            {
                // Converter only path: Conv(src.X) or Conv(src.X!) depending on nullability.
                // The '!' null-forgiving operator is needed ONLY when BOTH hold:
                //   (a) the source member is a possibly-null reference (nullable-annotated or
                //       oblivious) — SourceIsNullableRef, set precisely at MemberMap construction via
                //       SourceMayBeNullRef; value types (enums, numerics, Nullable<T>) and
                //       non-nullable references are false and so never get a spurious '!', and
                //   (b) the converter's parameter is NON-nullable. The synthesized scalar/nested
                //       converters (__DwarfMap_Num_/_StrParse_/_EnumName_/_Obj_ …) take a non-null
                //       parameter (and null-guard internally, so '!' is safe), whereas the
                //       collection/dictionary helpers (__DwarfMapColl/__DwarfMapDict/__DwarfBlit/
                //       __DwarfWiden) take a NULLABLE parameter and handle null→empty themselves, so
                //       they never need '!'. The `__DwarfMap_` prefix (with the trailing underscore)
                //       distinguishes the former from the latter.
                // Recursion-capable converters always receive the source through a null-guarded
                // helper, hence the ConverterNeedsDepthCtx clause forces '!' regardless.
                var needsBang = member.ConverterNeedsDepthCtx
                    || (member.SourceIsNullableRef
                        && member.ConverterMethod!.StartsWith("__DwarfMap_", System.StringComparison.Ordinal));
                if (member.ConverterNeedsDepthCtx)
                    sb.Append(member.ConverterMethod).Append('(')
                      .Append(paramName).Append('.').Append(member.SourceName)
                      .Append(needsBang ? "!" : "").Append(", ")
                      .Append(ctxVarName).Append(", ").Append(depthArg).Append(')');
                else
                    sb.Append(member.ConverterMethod).Append('(')
                      .Append(paramName).Append('.').Append(member.SourceName)
                      .Append(needsBang ? "!)" : ")");
            }
        }
        else
        {
            sb.Append(innerAccess);
        }
    }
}
