// SPDX-License-Identifier: GPL-2.0-only
using System.Text;
using DwarfMapper.Generator.Model;

namespace DwarfMapper.Generator.Pipeline;

internal static class MapEmitter
{
    public static string Emit(MapperClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// SPDX-License-Identifier: GPL-2.0-only");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(model.Accessibility).Append(" partial class ").AppendLine(model.ClassName);
        sb.AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, method, "    ");
        }

        foreach (var synth in model.SynthesizedMethods)
        {
            sb.AppendLine();
            sb.Append(synth.Code);
        }

        foreach (var rt in model.RoundTrips)
        {
            sb.AppendLine();
            sb.Append("    public void VerifyRoundTrip_").Append(rt.ForwardName).AppendLine("(int seed = 12345, int iterations = 100)");
            sb.Append("        => global::DwarfMapper.Testing.RoundTrip.Verify<")
              .Append(rt.SourceTypeFullName).Append(", ").Append(rt.DtoTypeFullName).Append(">(")
              .Append(rt.ForwardName).Append(", ").Append(rt.BackwardName).AppendLine(", seed, iterations);");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, MapMethodModel method, string indent)
    {
        // ── Determine depth-guard context ────────────────────────────────────────
        // A synthesized method that is recursion-capable gets extra (ctx, depth) parameters
        // and a depth guard at the top of its body.
        // A public (partial) method that calls recursion-capable synthesized methods creates
        // a DwarfRefContext upfront and passes it with depth=0 to the first tracked calls.
        var isSynthesizedRecursive = !method.IsPartial && method.IsRecursionCapable;
        var isPublicWithCtx = method.IsPartial && method.IsRecursionCapable;

        // Param names used in emission:
        //   public-with-ctx     : ctx variable = "__dwarf_ctx", depth passed = "0"
        //   synthesized-recursive: ctx param   = "ctx",         depth passed = "depth + 1"
        var ctxVarName  = isPublicWithCtx ? "__dwarf_ctx" : "ctx";
        var depthPassFwd = isSynthesizedRecursive ? "depth + 1" : "0";

        // IsPartial=true → user-declared partial: emit "public partial T Name(S s)"
        // IsPartial=false → synthesized private: plain or depth-guarded
        if (method.IsPartial)
        {
            // Public declared method — signature never changes (no ctx param for callers).
            sb.Append(indent).Append(method.Accessibility).Append(" partial ")
              .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
              .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName).AppendLine(")");
        }
        else if (isSynthesizedRecursive)
        {
            // Depth-guarded synthesized private method: extra (DwarfRefContext ctx, int depth) params.
            sb.Append(indent).Append("private ")
              .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
              .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName)
              .Append(", global::DwarfMapper.DwarfRefContext ctx, int depth")
              .AppendLine(")");
        }
        else
        {
            sb.Append(indent).Append("private ")
              .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
              .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName).AppendLine(")");
        }
        sb.Append(indent).AppendLine("{");

        if (method.ParameterIsReferenceType)
        {
            if (method.IsPartial)
            {
                // Public partial mapper: null source is a programming error → loud ArgumentNullException.
                sb.Append(indent).Append("    if (").Append(method.ParameterName)
                  .Append(" is null) throw new global::System.ArgumentNullException(nameof(")
                  .Append(method.ParameterName).AppendLine("));");
            }
            else if (method.ReturnIsReferenceType)
            {
                // Synthesized private nested mapper with a REFERENCE target: null source → null target
                // (defensive, not a throw). The calling mapper owns the outer null-check.
                sb.Append(indent).Append("    if (").Append(method.ParameterName)
                  .AppendLine(" is null) return null!;");
            }
            else
            {
                // Synthesized private nested mapper with a VALUE-TYPE target: cannot return null
                // (would be CS0037), so a null source is a loud failure rather than a silent default.
                sb.Append(indent).Append("    if (").Append(method.ParameterName)
                  .Append(" is null) throw new global::System.InvalidOperationException(\"Cannot map a null '")
                  .Append(method.ParameterTypeFullName)
                  .Append("' to value-type '").Append(method.ReturnTypeFullName).AppendLine("'.\");");
            }
        }

        // ── Depth guard (synthesized recursion-capable methods only) ────────────
        // Condition: depth >= ctx.MaxDepth (not strictly >, so that MaxDepth=8 allows depths 0..7
        // and throws at depth 8 — meaning chains of length > MaxDepth throw as specified).
        if (isSynthesizedRecursive)
        {
            sb.Append(indent).AppendLine("    if (depth >= ctx.MaxDepth)");
            sb.Append(indent).Append("        throw new global::DwarfMapper.DwarfMappingDepthException(ctx.MaxDepth, depth);");
            sb.AppendLine();
        }

        // ── DwarfRefContext creation (public methods calling recursion-capable pairs) ─
        if (isPublicWithCtx)
        {
            sb.Append(indent).Append("    var __dwarf_ctx = new global::DwarfMapper.DwarfRefContext(")
              .Append(method.MaxDepth.ToString(System.Globalization.CultureInfo.InvariantCulture));
            // Plan 19 C2: Preserve mode passes preserve:true to allocate the identity map.
            if (method.IsPreserveMode)
                sb.Append(", true");
            sb.AppendLine(");");
        }

        if (method.IsProjection)
        {
            sb.Append(indent).Append("    return global::System.Linq.Queryable.Select(")
              .Append(method.ParameterName).Append(", __s => ");

            var projMembers = method.ProjectionMembers;

            if (projMembers.Count == 1 && projMembers[0].TargetName.Length == 0)
            {
                // Ctor-only projection: the entire lambda body is the single inline expression.
                // e.g.  __s => new global::D.DstRec(x: __s.X, y: __s.Y)
                sb.Append(projMembers[0].InlineExpr).AppendLine(");");
            }
            else if (projMembers.Count > 0)
            {
                // Member-init projection with inline expression fragments (Plan 19D recursive resolver).
                sb.AppendLine("new " + method.ElementTargetTypeFullName);
                sb.Append(indent).AppendLine("    {");
                foreach (var pm in projMembers)
                {
                    sb.Append(indent).Append("        ").Append(pm.TargetName)
                      .Append(" = ").Append(pm.InlineExpr).AppendLine(",");
                }
                sb.Append(indent).AppendLine("    });");
            }
            else
            {
                // Fallback: legacy flat Members path (backward compat / error-case placeholder).
                sb.AppendLine("new " + method.ElementTargetTypeFullName);
                sb.Append(indent).AppendLine("    {");
                foreach (var member in method.Members)
                {
                    sb.Append(indent).Append("        ").Append(member.TargetName)
                      .Append(" = __s.").Append(member.SourceName).AppendLine(",");
                }
                sb.Append(indent).AppendLine("    });");
            }

            sb.Append(indent).AppendLine("}");
            return;
        }

        foreach (var before in method.BeforeHooks)
        {
            sb.Append(indent).Append("    ").Append(before).Append('(').Append(method.ParameterName).AppendLine(");");
        }

        var hasCtorArgs = method.ConstructorArguments.Count > 0;
        var hasInitMembers = method.Members.Count > 0;
        var hasAfter = method.AfterHooks.Count > 0;

        // ── Plan 19 C2: Register-before-populate (Preserve mode, recursion-capable) ──
        // Both synthesized recursion-capable methods AND public methods under Preserve mode
        // use register-before-populate to reconstruct arbitrary topologies:
        //   1. Check identity map: if already registered, return the cached target.
        //   2. Construct the target (ctor args only).
        //   3. Register in the identity map BEFORE populating members → breaks ALL cycles.
        //   4. Populate members via individual assignment statements.
        //   5. Return.
        //
        // The public method MUST also register-before-populate because the public source object
        // (`n`) can be encountered again via a recursive call (e.g. n.Self = n → self-loop;
        // a.Next = b, b.Next = a → 2-node cycle). If we don't register before populating,
        // the back-edge call re-constructs a NEW target instead of returning the in-progress one.
        //
        // Gate: isPreserve AND source is reference type (value types are never tracked; the
        // null check above has already returned/thrown for null sources).
        if (method.IsPreserveMode && method.ParameterIsReferenceType
            && (isSynthesizedRecursive || isPublicWithCtx))
        {
            EmitPreserveRegisterBeforePopulate(sb, method, indent, ctxVarName, depthPassFwd, isPublicWithCtx);
            sb.Append(indent).AppendLine("}");
            return;
        }

        // Begin construction expression: "var __dwarf_target = new T(...)" or "return new T(...)".
        sb.Append(indent).Append("    ").Append(hasAfter ? "var __dwarf_target = new " : "return new ")
          .Append(method.ReturnTypeFullName);

        if (hasCtorArgs)
        {
            // Named constructor arguments (clarity + safe against reordering).
            sb.AppendLine("(");
            var ctorArgs = method.ConstructorArguments;
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                var arg = ctorArgs[i];
                sb.Append(indent).Append("        ").Append(arg.TargetName).Append(": ");
                AppendValueExpression(sb, arg, method.ParameterName, ctxVarName, depthPassFwd);
                if (i < ctorArgs.Count - 1)
                    sb.AppendLine(",");
                else
                    sb.Append(')');
            }

            if (hasInitMembers)
            {
                sb.AppendLine();
                sb.Append(indent).AppendLine("    {");
                foreach (var member in method.Members)
                {
                    sb.Append(indent).Append("        ").Append(member.TargetName).Append(" = ");
                    AppendValueExpression(sb, member, method.ParameterName, ctxVarName, depthPassFwd);
                    sb.AppendLine(",");
                }
                sb.Append(indent).AppendLine("    };");
            }
            else
            {
                sb.AppendLine(";");
            }
        }
        else
        {
            // Original object-initializer only path (no ctor args).
            sb.AppendLine();
            sb.Append(indent).AppendLine("    {");
            foreach (var member in method.Members)
            {
                sb.Append(indent).Append("        ").Append(member.TargetName).Append(" = ");
                AppendValueExpression(sb, member, method.ParameterName, ctxVarName, depthPassFwd);
                sb.AppendLine(",");
            }
            sb.Append(indent).AppendLine("    };");
        }

        if (hasAfter)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("    ").Append(after.Name).Append('(');
                if (after.TakesSource)
                {
                    sb.Append(method.ParameterName).Append(", ");
                }
                if (after.TargetByRef)
                {
                    sb.Append("ref ");
                }
                sb.Append("__dwarf_target").AppendLine(");");
            }
            sb.Append(indent).Append("    return __dwarf_target;").AppendLine();
        }

        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    /// Emits the register-before-populate multi-statement form for a recursion-capable
    /// method under <c>ReferenceHandling = Preserve</c>.
    ///
    /// For synthesized private methods:
    /// <code>
    ///   if (ctx.TryGetReference(s, out var __dwarf_cached)) return (T)__dwarf_cached;
    ///   var __dwarf_t = new T(ctorArg1: ..., ctorArg2: ...);
    ///   ctx.SetReference(s, __dwarf_t);
    ///   __dwarf_t.Member1 = ...;
    ///   return __dwarf_t;
    /// </code>
    ///
    /// For public partial methods (isPublicMethod=true):
    /// <code>
    ///   // Before hooks run first (if any)
    ///   if (__dwarf_ctx.TryGetReference(n, out var __dwarf_cached)) return (T)__dwarf_cached;
    ///   var __dwarf_t = new T(...);
    ///   __dwarf_ctx.SetReference(n, __dwarf_t);
    ///   __dwarf_t.Member1 = ...;
    ///   // After hooks run on __dwarf_t (if any)
    ///   return __dwarf_t;
    /// </code>
    ///
    /// The TryGetReference/SetReference checks use the reference-identity comparer
    /// (ReferenceEqualityComparer.Instance) so value-equal records are never merged.
    /// </summary>
    private static void EmitPreserveRegisterBeforePopulate(
        StringBuilder sb, MapMethodModel method, string indent,
        string ctxVarName, string depthPassFwd, bool isPublicMethod)
    {
        var p = method.ParameterName;

        // Before hooks (public methods only).
        if (isPublicMethod)
        {
            foreach (var before in method.BeforeHooks)
            {
                sb.Append(indent).Append("    ").Append(before).Append('(').Append(p).AppendLine(");");
            }
        }

        // Step 1: Identity-map check — if already mapped, return the cached target.
        // Cast is safe: the identity map is keyed by the source object; the value was stored
        // by this same method, so it is always of type T.
        sb.Append(indent).Append("    if (").Append(ctxVarName).Append(".TryGetReference(")
          .Append(p).Append(", out var __dwarf_cached)) return (")
          .Append(method.ReturnTypeFullName).AppendLine(")__dwarf_cached;");

        // Step 2: Construct target. For the register-before-populate algorithm, the ctor
        // must be called WITHOUT graph-node members that participate in the cycle.
        // DWARF030 is emitted at generator time for any ctor arg that is recursion-capable.
        var hasCtorArgs = method.ConstructorArguments.Count > 0;
        sb.Append(indent).Append("    var __dwarf_t = new ").Append(method.ReturnTypeFullName);

        if (hasCtorArgs)
        {
            sb.AppendLine("(");
            var ctorArgs = method.ConstructorArguments;
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                var arg = ctorArgs[i];
                sb.Append(indent).Append("        ").Append(arg.TargetName).Append(": ");
                AppendValueExpression(sb, arg, p, ctxVarName, depthPassFwd);
                if (i < ctorArgs.Count - 1)
                    sb.AppendLine(",");
                else
                    sb.AppendLine(")");
            }
        }
        else
        {
            sb.AppendLine("();");
        }

        // Step 3: Register BEFORE populating members — the critical invariant.
        // This ensures any recursive call to map the same source object returns THIS instance,
        // not a newly constructed duplicate. Breaks all cycles (self-loops, 2-node, N-node, diamonds).
        sb.Append(indent).Append("    ").Append(ctxVarName).Append(".SetReference(")
          .Append(p).AppendLine(", __dwarf_t);");

        // Step 4: Populate settable members via individual assignment statements.
        // Safe because __dwarf_t is in the identity map before any member recursion.
        foreach (var member in method.Members)
        {
            sb.Append(indent).Append("    __dwarf_t.").Append(member.TargetName).Append(" = ");
            AppendValueExpression(sb, member, p, ctxVarName, depthPassFwd);
            sb.AppendLine(";");
        }

        // After hooks (public methods only), then return.
        if (isPublicMethod && method.AfterHooks.Count > 0)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("    ").Append(after.Name).Append('(');
                if (after.TakesSource) sb.Append(p).Append(", ");
                if (after.TargetByRef) sb.Append("ref ");
                sb.Append("__dwarf_t").AppendLine(");");
            }
        }

        // Step 5: Return the fully-populated target.
        sb.Append(indent).AppendLine("    return __dwarf_t;");
    }

    /// <summary>
    /// Append the value expression for a single mapping (ctor arg or object-initializer member)
    /// to <paramref name="sb"/>. Does NOT append a trailing comma or newline.
    /// </summary>
    /// <param name="ctxVarName">
    /// Name of the <c>DwarfRefContext</c> variable in scope (e.g. <c>"ctx"</c> or
    /// <c>"__dwarf_ctx"</c>). Only used when <see cref="MemberMap.ConverterNeedsDepthCtx"/> is true.
    /// </param>
    /// <param name="depthArg">
    /// The depth argument to forward (e.g. <c>"depth + 1"</c> from a recursion-capable synthesized
    /// method, or <c>"0"</c> from the public entry point). Only used when
    /// <see cref="MemberMap.ConverterNeedsDepthCtx"/> is true.
    /// </param>
    private static void AppendValueExpression(
        StringBuilder sb, MemberMap member, string paramName,
        string ctxVarName = "ctx", string depthArg = "0")
    {
        // NullableProject: both source and target are Nullable<T>. Emit null-preserving ternary:
        //   src.X.HasValue ? Conv(src.X.Value) : null
        // C# 9+ target-typed conditional unifies U (from Conv) and null into U?.
        if (member.NullHandling == Model.NullHandling.NullableProject)
        {
            var srcExpr = paramName + "." + member.SourceName;
            if (member.ConverterMethod is not null)
            {
                sb.Append(srcExpr).Append(".HasValue ? ")
                  .Append(member.ConverterMethod).Append('(').Append(srcExpr).Append(".Value) : null");
            }
            else
            {
                // Defensive fallback: T?→U? where T→U is implicit (direct assignment).
                sb.Append(srcExpr);
            }
            return;
        }

        // Build the "inner value access" — the nullable-unwrapped (or plain) source expression.
        string innerAccess;
        switch (member.NullHandling)
        {
            case Model.NullHandling.ThrowIfNull:
                innerAccess = paramName + "." + member.SourceName
                    + " ?? throw new global::System.InvalidOperationException(\"Source member '"
                    + member.SourceName + "' was null\")";
                break;
            case Model.NullHandling.ValueOrDefault:
                innerAccess = paramName + "." + member.SourceName + ".GetValueOrDefault()";
                break;
            default:
                innerAccess = paramName + "." + member.SourceName;
                break;
        }

        // Wrap the inner access with the converter if present.
        if (member.ConverterMethod is not null)
        {
            if (member.NullHandling != Model.NullHandling.None)
            {
                // Both converter and null-handling: Conv(src.X ?? throw ...) or Conv(src.X.GetValueOrDefault())
                if (member.ConverterNeedsDepthCtx)
                    sb.Append(member.ConverterMethod).Append('(').Append(innerAccess)
                      .Append(", ").Append(ctxVarName).Append(", ").Append(depthArg).Append(')');
                else
                    sb.Append(member.ConverterMethod).Append('(').Append(innerAccess).Append(')');
            }
            else
            {
                // Converter only path: Conv(src.X) or Conv(src.X!) depending on nullability.
                // The '!' null-forgiving operator is needed when the source member is a nullable
                // reference type (e.g. Node? Next) but the converter expects non-null (Node).
                // Synthesized nested mappers (__DwarfMap_Obj_... / __DwarfMap_Depth_...) always
                // begin with a null guard (if (s is null) return null!) so the '!' is safe and
                // suppresses CS8604. User-declared converters receive the source as-is (no '!').
                var needsBang = member.ConverterNeedsDepthCtx
                    || member.SourceIsNullableRef
                    || member.ConverterMethod!.StartsWith("__DwarfMap_", System.StringComparison.Ordinal);
                if (member.ConverterNeedsDepthCtx)
                    sb.Append(member.ConverterMethod).Append('(')
                      .Append(paramName).Append('.').Append(member.SourceName)
                      .Append(needsBang ? "!" : "").Append(", ")
                      .Append(ctxVarName).Append(", ").Append(depthArg).Append(')');
                else
                    sb.Append(member.ConverterMethod).Append('(')
                      .Append(paramName).Append('.').Append(member.SourceName)
                      .Append(needsBang ? "!)" : ")");
            }
        }
        else
        {
            sb.Append(innerAccess);
        }
    }
}
