// SPDX-License-Identifier: GPL-2.0-only
using System.Text;
using DwarfMapper.Generator.Model;

namespace DwarfMapper.Generator.Pipeline;

internal static class MapEmitter
{
    public static string Emit(MapperClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// SPDX-License-Identifier: GPL-2.0-only");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(model.Accessibility).Append(" partial class ").AppendLine(model.ClassName);
        sb.AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, method, "    ");
        }

        foreach (var synth in model.SynthesizedMethods)
        {
            sb.AppendLine();
            sb.Append(synth.Code);
        }

        foreach (var rt in model.RoundTrips)
        {
            sb.AppendLine();
            sb.Append("    public void VerifyRoundTrip_").Append(rt.ForwardName).AppendLine("(int seed = 12345, int iterations = 100)");
            sb.Append("        => global::DwarfMapper.Testing.RoundTrip.Verify<")
              .Append(rt.SourceTypeFullName).Append(", ").Append(rt.DtoTypeFullName).Append(">(")
              .Append(rt.ForwardName).Append(", ").Append(rt.BackwardName).AppendLine(", seed, iterations);");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, MapMethodModel method, string indent)
    {
        sb.Append(indent).Append(method.Accessibility).Append(" partial ")
          .Append(method.ReturnTypeFullName).Append(' ').Append(method.MethodName)
          .Append('(').Append(method.ParameterTypeFullName).Append(' ').Append(method.ParameterName).AppendLine(")");
        sb.Append(indent).AppendLine("{");

        if (method.ParameterIsReferenceType)
        {
            sb.Append(indent).Append("    if (").Append(method.ParameterName)
              .Append(" is null) throw new global::System.ArgumentNullException(nameof(")
              .Append(method.ParameterName).AppendLine("));");
        }

        if (method.IsProjection)
        {
            sb.Append(indent).Append("    return global::System.Linq.Queryable.Select(")
              .Append(method.ParameterName).AppendLine(", __s => new " + method.ElementTargetTypeFullName);
            sb.Append(indent).AppendLine("    {");
            foreach (var member in method.Members)
            {
                sb.Append(indent).Append("        ").Append(member.TargetName)
                  .Append(" = __s.").Append(member.SourceName).AppendLine(",");
            }
            sb.Append(indent).AppendLine("    });");
            sb.Append(indent).AppendLine("}");
            return;
        }

        foreach (var before in method.BeforeHooks)
        {
            sb.Append(indent).Append("    ").Append(before).Append('(').Append(method.ParameterName).AppendLine(");");
        }

        var hasAfter = method.AfterHooks.Count > 0;
        sb.Append(indent).Append("    ").Append(hasAfter ? "var __dwarf_target = new " : "return new ").AppendLine(method.ReturnTypeFullName);
        sb.Append(indent).AppendLine("    {");
        foreach (var member in method.Members)
        {
            sb.Append(indent).Append("        ").Append(member.TargetName).Append(" = ");
            // Build the "inner value access" — the nullable-unwrapped (or plain) source expression.
            // When NullHandling is set, we unwrap the nullable first; otherwise it is a plain access.
            string innerAccess;
            switch (member.NullHandling)
            {
                case Model.NullHandling.ThrowIfNull:
                    innerAccess = method.ParameterName + "." + member.SourceName
                        + " ?? throw new global::System.InvalidOperationException(\"Source member '"
                        + member.SourceName + "' was null\")";
                    break;
                case Model.NullHandling.ValueOrDefault:
                    innerAccess = method.ParameterName + "." + member.SourceName + ".GetValueOrDefault()";
                    break;
                default:
                    innerAccess = method.ParameterName + "." + member.SourceName;
                    break;
            }
            // Wrap the inner access with the converter if present.
            if (member.ConverterMethod is not null)
            {
                if (member.NullHandling != Model.NullHandling.None)
                {
                    // Both converter and null-handling: Conv(src.X ?? throw ...) or Conv(src.X.GetValueOrDefault())
                    sb.Append(member.ConverterMethod).Append('(').Append(innerAccess).Append(')');
                }
                else
                {
                    // Converter only (original path): Conv(src.X)
                    sb.Append(member.ConverterMethod).Append('(')
                      .Append(method.ParameterName).Append('.').Append(member.SourceName).Append(')');
                }
            }
            else
            {
                sb.Append(innerAccess);
            }
            sb.AppendLine(",");
        }
        sb.Append(indent).AppendLine("    };");

        if (hasAfter)
        {
            foreach (var after in method.AfterHooks)
            {
                sb.Append(indent).Append("    ").Append(after.Name).Append('(');
                if (after.TakesSource)
                {
                    sb.Append(method.ParameterName).Append(", ");
                }
                if (after.TargetByRef)
                {
                    sb.Append("ref ");
                }
                sb.Append("__dwarf_target").AppendLine(");");
            }
            sb.Append(indent).Append("    return __dwarf_target;").AppendLine();
        }

        sb.Append(indent).AppendLine("}");
    }
}
