// SPDX-License-Identifier: GPL-2.0-only

using System.Text;
using DwarfMapper.Generator.Model;

namespace DwarfMapper.Generator.Pipeline
{
    /// <summary>
    ///     Writes a <see cref="ViewModel" /> out as a nested <c>public readonly ref struct</c> on the mapper
    ///     class, plus — for a view a <c>[GenerateView]</c> declared — the <c>View(TSource)</c> factory beside it.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         The <c>ref struct</c> is the CONTRACT, not a limitation of the implementation: it cannot be boxed,
    ///         stored in a field, captured by a lambda, or held across an <c>await</c>, so the compiler enforces
    ///         that the view never outlives the source it borrows. That is what makes reading through to a live
    ///         source safe, and it is why the type is emitted as one even though nothing in the body requires it.
    ///     </para>
    ///     <para>
    ///         Every property is an EXPRESSION over <c>_s</c>, re-evaluated on each access. The view allocates
    ///         nothing; a converter it calls may still allocate on its own account (an <c>int -&gt; string</c>
    ///         edge builds a string), and it does so once per read rather than once per map.
    ///     </para>
    /// </remarks>
    internal static class ViewEmitter
    {
        /// <summary>Emits one view type, and its factory when the view was declared rather than reached.</summary>
        /// <param name="sb">The mapper class body being written.</param>
        /// <param name="view">The view to emit.</param>
        /// <param name="mapperName">The mapper class's own name, for the owner field's type.</param>
        /// <param name="indent">The mapper class body's indent.</param>
        public static void Emit(StringBuilder sb, ViewModel view, string mapperName, string indent)
        {
            var inner = indent + "    ";

            sb.AppendLine();
            sb.Append(indent).Append("/// <summary>Generated by DwarfMapper — a ZERO-COPY view of <c>")
                .Append(XmlEscape(view.SourceTypeFullName))
                .AppendLine("</c>.</summary>");
            sb.Append(indent)
                .AppendLine("/// <remarks>Every property is evaluated on access against the source this view borrows. It is a <c>ref struct</c>, so it cannot be stored, boxed, captured or held across an <c>await</c>: consume it at once, and use <c>Map</c> where the result is kept.</remarks>");
            sb.Append(indent).Append("public readonly ref struct ").AppendLine(view.ViewTypeName);
            sb.Append(indent).AppendLine("{");

            if (view.NeedsOwner)
            {
                sb.Append(inner).Append("private readonly ").Append(mapperName).AppendLine(" _m;");
            }

            sb.Append(inner).Append("private readonly ").Append(view.SourceTypeFullName).AppendLine(" _s;");
            sb.AppendLine();

            // internal, not public: a nested view is constructed by the view that holds it, which is a sibling
            // nested type of the same mapper, and the factory below is the public way in. A public constructor
            // would also let a caller build a view over a source the mapping was never resolved against.
            sb.Append(inner).Append("internal ").Append(view.ViewTypeName).Append('(');
            if (view.NeedsOwner)
            {
                sb.Append(mapperName).Append(" owner, ");
            }

            sb.Append(view.SourceTypeFullName).AppendLine(" source)");
            sb.Append(inner).AppendLine("{");
            sb.Append(inner).AppendLine("    global::System.ArgumentNullException.ThrowIfNull(source);");
            if (view.NeedsOwner)
            {
                sb.Append(inner).AppendLine("    _m = owner;");
            }

            sb.Append(inner).AppendLine("    _s = source;");
            sb.Append(inner).AppendLine("}");
            sb.AppendLine();

            // A view reached through a NULL nested member is `default`, whose `_s` is null however the field is
            // annotated. HasValue is how a caller asks, and it is emitted on every view rather than only on the
            // ones a nullable member can produce: one view type may be reached from a nullable member in one
            // place and a non-nullable one in another, and a property that exists only sometimes is worse than a
            // property that is sometimes always true.
            sb.Append(inner)
                .AppendLine("/// <summary>Whether this view has a source. <c>false</c> only for the <c>default</c> view a null nested member yields.</summary>");
            sb.Append(inner).AppendLine("public bool HasValue => _s is not null;");

            foreach (var member in view.Members)
            {
                sb.Append(inner).Append("public ").Append(member.TypeFullName).Append(' ').Append(member.Name)
                    .Append(" => ");
                AppendMemberExpression(sb, member);
                sb.AppendLine(";");
            }

            sb.Append(indent).AppendLine("}");

            if (!view.EmitFactory)
            {
                return;
            }

            sb.AppendLine();
            sb.Append(indent).Append("/// <summary>Generated by DwarfMapper — creates a zero-copy <c>")
                .Append(XmlEscape(view.ViewTypeName)).AppendLine("</c> over <paramref name=\"source\" />.</summary>");
            sb.Append(indent).Append("public ").Append(view.ViewTypeName).Append(" View(")
                .Append(view.SourceTypeFullName).Append(" source) => new ").Append(view.ViewTypeName).Append('(');
            if (view.NeedsOwner)
            {
                sb.Append("this, ");
            }

            sb.AppendLine("source);");
        }

        private static void AppendMemberExpression(StringBuilder sb, ViewMemberModel member)
        {
            if (member.NestedViewTypeName is not null)
            {
                // A null source member yields `default` — a view whose HasValue is false — rather than a
                // constructor call that would throw on a member the create map maps to null perfectly happily.
                if (member.NestedSourceIsNullable)
                {
                    sb.Append("_s.").Append(member.NestedSourceMember).Append(" is null ? default : ");
                }

                sb.Append("new ").Append(member.NestedViewTypeName).Append('(');
                if (member.NestedViewNeedsOwner)
                {
                    // The child's own resolution named an instance member of the mapper, so its constructor
                    // takes the owner. The parent passes it whether or not IT needs one for itself — which is
                    // why NeedsOwner propagates UP the nesting graph before anything is emitted.
                    sb.Append("_m, ");
                }

                sb.Append("_s.").Append(member.NestedSourceMember).Append(')');
                return;
            }

            var value = member.Value!;

            // [MapProperty(When = …)] and SkipNullSourceMembers both say "leave the destination's own value
            // alone". A view has no destination instance, so the destination's own value is `default` — the
            // faithful translation of the create map's `if (…) target.M = …;` into an expression. Forgiven
            // because `default` for a non-nullable reference is exactly the value the create map would have
            // left there, and CS8603 out of a .g.cs is not suppressible by the consumer.
            var guard = value.WhenPredicate is not null
                ? value.WhenPredicate + "(_s)"
                : value.SkipIfSourceNull
                    ? "_s." + value.EmitSourceName + " is not null"
                    : null;

            if (guard is not null)
            {
                sb.Append(guard).Append(" ? ");
            }

            MapEmitter.AppendValueExpression(sb, value, "_s");

            if (guard is not null)
            {
                sb.Append(" : default!");
            }
        }

        private static string XmlEscape(string s)
        {
            return s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
